import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const conciergeStyles = StyleSheet.create({
  partnerCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.lg,
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  avatarLg: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontFamily: "Inter_900Black",
    color: COLORS.white,
    fontSize: 16,
    letterSpacing: 0.6,
  },
  partnerBody: {
    flex: 1,
    minWidth: 260,
    gap: 6,
  },
  partnerName: {
    fontFamily: "Inter_900Black",
    fontSize: 18,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
  },
  statusNeon: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.neonOrange,
  },
  statusText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: COLORS.portalInk,
  },
  partnerRole: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  partnerSince: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: SPACING.xs,
  },
  tag: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  tagText: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  actionsCol: {
    gap: 10,
    minWidth: 240,
    flexGrow: 0,
  },
  ctaPrimary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  ctaPrimaryText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.white,
  },
  ctaGhost: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  ctaGhostText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  ctaWa: {
    backgroundColor: "#1DAA5B",
    borderColor: "rgba(0,0,0,0.08)",
  },
  ctaWaText: {
    color: COLORS.white,
  },
  g4: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: SPACING.lg,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: "23%",
    minWidth: 200,
    borderRadius: RADIUS.lg,
  },
  statTop: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: SPACING.md,
  },
  statName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  statMeta: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  statBot: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 10,
  },
  statBig: {
    fontFamily: "Inter_900Black",
    fontSize: 26,
    letterSpacing: -0.8,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  statBigRevenue: {
    color: COLORS.neonOrange,
  },
  statSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  badgeAmber: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.accentAmber,
    backgroundColor: COLORS.neonOrange,
  },
  badgeAmberText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.5,
    color: COLORS.white,
    textTransform: "uppercase",
  },
  badgeNeutral: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  badgeNeutralText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.5,
    color: COLORS.ink3,
    textTransform: "uppercase",
  },
  badgeLive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  badgeLiveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: COLORS.neonYellow,
    shadowColor: COLORS.neonYellow,
    shadowOpacity: 0.55,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
    elevation: 2,
  },
  badgeLiveText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.5,
    color: COLORS.portalInk,
    textTransform: "uppercase",
  },
  oppItem: {
    paddingVertical: SPACING.md,
    gap: 10,
  },
  oppHead: {
    flexDirection: "row",
    gap: SPACING.md,
    alignItems: "flex-start",
  },
  oppIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  oppMain: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  oppTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  oppSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
    lineHeight: 15,
  },
  oppLift: {
    fontFamily: "Inter_900Black",
    fontSize: 16,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  oppLiftUnit: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  oppBtn: {
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.portalInk,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
  },
  oppBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  menuRank: {
    width: 54,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  menuRankStar: {
    backgroundColor: "rgba(255, 138, 0, 0.16)",
    borderColor: "rgba(255, 138, 0, 0.35)",
  },
  menuRankDog: {
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    borderColor: "rgba(239, 68, 68, 0.35)",
  },
  menuRankHold: {
    backgroundColor: "rgba(207, 207, 207, 0.55)",
  },
  menuRankText: {
    fontFamily: "Inter_900Black",
    fontSize: 10,
    letterSpacing: 0.6,
    color: COLORS.portalInk,
  },
  menuBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  menuName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  menuSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    lineHeight: 15,
  },
  menuMini: {
    alignItems: "flex-end",
    gap: 2,
  },
  menuMiniN: {
    fontFamily: "Inter_900Black",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  menuMiniL: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  menuFixBtn: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
  },
  menuFixBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  g21: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "stretch",
  },
  g21Main: {
    flexGrow: 2,
    flexBasis: "62%",
    minWidth: 380,
  },
  g21Side: {
    flexGrow: 1,
    flexBasis: "32%",
    minWidth: 300,
  },
  ticket: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  tStatus: {
    width: 110,
    paddingVertical: 8,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  tStatusText: {
    fontFamily: "Inter_900Black",
    fontSize: 9,
    letterSpacing: 0.6,
    color: COLORS.portalInk,
  },
  tProgress: { backgroundColor: "rgba(255, 138, 0, 0.18)" },
  tReview: { backgroundColor: "rgba(255, 229, 0, 0.22)" },
  tWait: { backgroundColor: "rgba(207, 207, 207, 0.55)" },
  tBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  tTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  tSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    lineHeight: 15,
  },
  tSteps: {
    flexDirection: "row",
    gap: 6,
  },
  step: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.chartMist,
  },
  stepDone: {
    backgroundColor: COLORS.secondary,
  },
  stepActive: {
    backgroundColor: COLORS.neonOrange,
  },
  escDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    lineHeight: 17,
    marginBottom: SPACING.md,
  },
  escWarn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 51, 85, 0.35)",
    backgroundColor: "rgba(255, 51, 85, 0.08)",
    marginBottom: SPACING.md,
  },
  escWarnText: {
    flex: 1,
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  escBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.neonRed,
  },
  escBtnText: {
    fontFamily: "Inter_900Black",
    fontSize: 12,
    color: COLORS.white,
  },
  escFoot: {
    marginTop: SPACING.sm,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
  },
  betaRow: {
    flexDirection: "row",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
    alignItems: "flex-start",
  },
  betaIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
  },
  betaBody: { flex: 1, gap: 4, minWidth: 0 },
  betaTitle: { fontFamily: "Inter_800ExtraBold", fontSize: 13, color: COLORS.portalInk },
  betaSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
    lineHeight: 15,
  },
  betaDetails: {
    marginTop: 6,
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  betaBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.portalInk,
    backgroundColor: COLORS.white,
  },
  betaBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  betaTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(34, 197, 94, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(34, 197, 94, 0.35)",
  },
  betaTagText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.portalInk,
  },
  event: {
    flexDirection: "row",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  eventDate: {
    width: 80,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  eventD: { fontFamily: "Inter_900Black", fontSize: 18, color: COLORS.white },
  eventM: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1,
    color: COLORS.white,
  },
  eventBody: { flex: 1, gap: 4, minWidth: 0 },
  eventTag: {
    fontFamily: "Inter_900Black",
    fontSize: 10,
    letterSpacing: 1,
    color: COLORS.neonOrange,
  },
  eventTitle: { fontFamily: "Inter_800ExtraBold", fontSize: 13, color: COLORS.portalInk },
  eventSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
    lineHeight: 15,
  },
  eventDetails: {
    marginTop: 6,
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  eventBtn: {
    alignSelf: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.portalInk,
  },
  eventBtnText: { fontFamily: "Inter_800ExtraBold", fontSize: 11, color: COLORS.white },
  auditRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  auditTitle: { fontFamily: "Inter_800ExtraBold", fontSize: 13, color: COLORS.portalInk },
  auditSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
    lineHeight: 15,
    maxWidth: 520,
  },
  auditBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  auditBtnText: { fontFamily: "Inter_800ExtraBold", fontSize: 12, color: COLORS.white },
  recentLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink4,
    marginBottom: 8,
  },
  auditHistRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  auditDate: {
    width: 90,
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  auditHistTitle: {
    flex: 1,
    minWidth: 180,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  auditTag: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.secondary,
  },
  goal: { gap: 8, paddingVertical: SPACING.sm },
  goalHead: { flexDirection: "row", justifyContent: "space-between", gap: 10 },
  goalTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    flex: 1,
  },
  goalPct: {
    fontFamily: "Inter_900Black",
    fontSize: 12,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  goalBar: {
    height: 10,
    borderRadius: 6,
    backgroundColor: COLORS.chartMist,
    overflow: "hidden",
  },
  goalFill: {
    height: "100%",
    borderRadius: 6,
    backgroundColor: COLORS.neonOrange,
  },
  goalSub: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: COLORS.ink4 },
  vaultDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    lineHeight: 17,
    marginBottom: SPACING.md,
  },
  vaultFile: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  vaultIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
  },
  vaultBody: { flex: 1, gap: 4, minWidth: 0 },
  vaultName: { fontFamily: "Inter_800ExtraBold", fontSize: 12, color: COLORS.portalInk },
  vaultSub: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: COLORS.ink4 },
  vaultTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  vaultTagText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.portalInk,
  },
  vaultTagPending: {
    backgroundColor: "rgba(255, 229, 0, 0.18)",
    borderColor: "rgba(255, 229, 0, 0.35)",
  },
  vidsDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    lineHeight: 17,
    marginBottom: SPACING.md,
  },
  vidItem: {
    flexDirection: "row",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
    alignItems: "center",
  },
  vidThumb: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
  },
  vidBody: { flex: 1, gap: 4, minWidth: 0 },
  vidTitle: { fontFamily: "Inter_800ExtraBold", fontSize: 12, color: COLORS.portalInk },
  vidSub: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: COLORS.ink4 },
  vidNew: {
    borderLeftWidth: 4,
    borderLeftColor: COLORS.neonOrange,
    paddingLeft: SPACING.sm,
  },
});
