import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContent: {
    paddingBottom: SPACING.xxl,
  },
  heroDisplay: {
    alignItems: "center",
    marginTop: SPACING.sm,
    marginBottom: 4,
  },
  heroAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
  },
  heroCurrency: {
    transform: [{ translateY: 4 }],
  },
  heroNumber: {
    fontFamily: "Inter_900Black",
    fontSize: 72,
    letterSpacing: -3,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  meta: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginTop: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  metaLeft: {
    flex: 1,
    minWidth: 120,
  },
  brandStack: {
    gap: 2,
  },
  brandName: {
    fontFamily: "Inter_900Black",
    fontSize: 12,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: COLORS.portalInk,
  },
  brandBranch: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink4,
    marginTop: 2,
  },
  metaMid: {
    flex: 1.4,
    alignItems: "center",
    gap: 4,
    minWidth: 200,
  },
  metaMidRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    flexWrap: "wrap",
  },
  metaMidText: {
    flexShrink: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    textAlign: "center",
    lineHeight: 18,
  },
  metaMidStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.trendPositiveDeep,
  },
  metaMidSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
  },
  metaMidLive: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  metaRight: {
    flex: 1,
    alignItems: "flex-end",
    minWidth: 120,
  },
  metaRightRtl: {
    alignItems: "flex-start",
  },
  metaTime: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    letterSpacing: -0.3,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  metaDate: {
    marginTop: 4,
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginBottom: SPACING.lg,
  },
  pgHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.lg,
    marginBottom: SPACING.md,
    flexWrap: "wrap",
  },
  pgHeadTitle: {
    flex: 1,
    minWidth: 220,
    gap: 0,
  },
  h1Light: {
    fontFamily: "Inter_400Regular",
    fontSize: 34,
    letterSpacing: -0.5,
    lineHeight: 38,
    color: COLORS.portalInk,
  },
  h1Strong: {
    fontFamily: "Inter_900Black",
    fontSize: 34,
    letterSpacing: -0.6,
    lineHeight: 38,
    color: COLORS.portalInk,
  },
  tag: {
    flex: 1,
    minWidth: 220,
    maxWidth: 320,
    paddingTop: 6,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
  },
  sectionHeadRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
    marginBottom: 10,
    flexWrap: "wrap",
  },
  sectionTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    letterSpacing: -0.3,
    color: COLORS.portalInk,
  },
  sectionCaption: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    minWidth: 160,
  },
  opsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: SPACING.sm,
  },
  opsCardWrap: {
    flexGrow: 1,
    flexBasis: "23%",
    minWidth: 160,
  },
  metricBig: {
    fontFamily: "Inter_500Medium",
    fontSize: 22,
    letterSpacing: -0.4,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  metricBigXl: {
    fontFamily: "Inter_900Black",
    fontSize: 28,
    letterSpacing: -0.6,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  finBigRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  statRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
  statText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    textAlign: "right",
  },
  statOk: {
    color: COLORS.trendPositive,
  },
  finHeadRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginTop: SPACING.md,
    marginBottom: 10,
    flexWrap: "wrap",
  },
  finHeadTitles: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    flex: 1,
    flexWrap: "wrap",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 3,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(0,0,0,0.04)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  badgeText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink2,
  },
  finGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "stretch",
    gap: 12,
    marginBottom: SPACING.sm,
  },
  finCardWrap: {
    flexGrow: 1,
    flexBasis: "31%",
    minWidth: 260,
    alignSelf: "stretch",
  },
  finCardEqualHeight: {
    flex: 1,
  },
  finThird: {
    flex: 1,
    flexBasis: "31%",
    minWidth: 260,
    alignSelf: "stretch",
    justifyContent: "space-between",
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  finThirdTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
    gap: SPACING.sm,
  },
  finThirdTitle: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  finThirdMeta: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink5,
  },
  liveMeta: {
    flexDirection: "row",
    alignItems: "center",
  },
  chartGrid: {
    gap: 12,
    marginTop: 4,
  },
  chartRow3: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "stretch",
  },
  chartRow2: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "stretch",
  },
  chartPanel: {
    flexGrow: 1,
    flexBasis: "31%",
    minWidth: 240,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  chartHead: {
    marginBottom: 8,
  },
  chartTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    letterSpacing: -0.2,
    color: COLORS.portalInk,
  },
  chartSub: {
    marginTop: 4,
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  speedLegend: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(0,0,0,0.06)",
    gap: SPACING.sm,
  },
  legendText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink3,
  },
  legendInline: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink3,
    flex: 1,
  },
  legendStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  legendOk: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.trendPositiveDeep,
  },
  legendRight: {
    textAlign: "right",
  },
  peakHeroMeta: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    color: COLORS.ink4,
    textAlign: "right",
  },
  peakHeroMetaHi: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.trendPositiveDeep,
  },
  rowRtl: {
    flexDirection: "row-reverse",
  },
});
