import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const mediaStyles = StyleSheet.create({
  metaCreatorStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.neonOrange,
  },
  displaySub: {
    marginTop: -8,
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.xs,
  },
  displaySubText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.portalInk,
    textAlign: "center",
  },
  displaySubMuted: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink4,
  },
  flexBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
    flexWrap: "wrap",
  },
  flexBetweenRtl: {
    flexDirection: "row-reverse",
  },
  panelTitleInline: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.ink4,
    marginBottom: 0,
  },
  badgeOk: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  badgeOkText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: COLORS.neonOrange,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.neonOrange,
  },
  badgeNeutral: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  badgeNeutralText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.4,
    color: COLORS.ink3,
    textTransform: "uppercase",
  },
  badgeAmber: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.accentAmber,
    backgroundColor: "rgba(239, 159, 39, 0.12)",
  },
  badgeAmberText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.3,
    color: COLORS.neonOrange,
  },
  heroEmpty: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 140,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: SPACING.md,
    gap: 8,
  },
  heroEmptyTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
    textAlign: "center",
  },
  heroEmptySub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
    lineHeight: 16,
  },
  mhActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  ghostSmBtn: {
    paddingVertical: 10,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  ghostSmBtnText: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  storiesRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  storyAdd: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.whiteSecondary,
  },
  storyPlus: {
    fontFamily: "Inter_900Black",
    fontSize: 28,
    color: COLORS.ink3,
    lineHeight: 32,
  },
  storyDrop: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.lg,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    gap: 6,
  },
  storyDropTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  storyDropSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
  },
  statusInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.whiteSecondary,
    paddingHorizontal: SPACING.sm,
    marginBottom: SPACING.md,
  },
  statusInput: {
    flex: 1,
    minHeight: 44,
    paddingVertical: 10,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  statusCount: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    marginLeft: SPACING.sm,
  },
  statusCountNum: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  statusPreview: {
    marginBottom: SPACING.md,
  },
  spLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink4,
    marginBottom: 8,
  },
  spBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  spDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.neonYellow,
  },
  spBadgeText: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.white,
  },
  presetsLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink4,
    marginBottom: 8,
  },
  presetsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  presetChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  presetChipText: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  ghostFullBtn: {
    marginTop: SPACING.md,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    backgroundColor: COLORS.whiteSecondary,
  },
  ghostFullBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  bioArea: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.portalInk,
    textAlignVertical: "top",
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: SPACING.xs,
  },
  bioCount: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    marginBottom: SPACING.md,
    textAlign: "right",
  },
  bioLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 0.8,
    color: COLORS.ink2,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  bioChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: SPACING.md,
  },
  vchip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  vchipOn: {
    backgroundColor: COLORS.portalInk,
    borderColor: COLORS.portalInk,
  },
  vchipText: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  vchipTextOn: {
    color: COLORS.white,
  },
  bioPublish: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: SPACING.sm,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  bioPublishText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.white,
  },
  cineWrap: {
    borderRadius: RADIUS.lg,
    overflow: "hidden",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    marginBottom: SPACING.md,
  },
  cineEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.whiteSecondary,
    gap: SPACING.sm,
  },
  cineEmptyTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  cineEmptySub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
    lineHeight: 16,
  },
  cineCap: {
    paddingVertical: 10,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  cineCapText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
    textAlign: "center",
  },
  cineOpts: {
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  cineOpt: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  cineOptText: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  g21: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "stretch",
  },
  g21Main: {
    flexGrow: 2,
    flexBasis: "58%",
    minWidth: 360,
  },
  g21Side: {
    flexGrow: 1,
    flexBasis: "32%",
    minWidth: 300,
  },
  socialRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  socialIc: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.whiteSecondary,
  },
  socialBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  socialNm: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  socialDs: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    lineHeight: 15,
  },
  connectBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.portalInk,
    backgroundColor: COLORS.white,
  },
  connectBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  syncTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    letterSpacing: 0.6,
    color: COLORS.portalInk,
    marginTop: SPACING.lg,
    marginBottom: SPACING.sm,
  },
  syncRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  syncRowRtl: {
    flexDirection: "row-reverse",
  },
  syncT: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    marginBottom: 4,
  },
  syncS: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    lineHeight: 15,
  },
  igFeedDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    lineHeight: 17,
    marginBottom: SPACING.md,
  },
  sfGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: SPACING.sm,
  },
  sfPost: {
    flexGrow: 1,
    flexBasis: "30%",
    minWidth: 96,
    aspectRatio: 1,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.chartMist,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    justifyContent: "flex-end",
    padding: 8,
  },
  sfMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  sfMetaText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    color: COLORS.ink3,
  },
  sfNote: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
    fontStyle: "italic",
  },
  moods: {
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  mood: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: 12,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  moodOn: {
    borderColor: COLORS.neonOrange,
    borderWidth: 2,
    backgroundColor: COLORS.white,
  },
  moodSwatch: {
    width: 36,
    height: 36,
    borderRadius: 10,
  },
  moodMorning: { backgroundColor: "#E8DCC8" },
  moodLunch: { backgroundColor: "#F4D03F" },
  moodDinner: { backgroundColor: "#5D4E37" },
  moodNight: { backgroundColor: "#1a1a2e" },
  moodBody: {
    flex: 1,
    gap: 2,
  },
  moodNm: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  moodTm: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  moodFoot: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    paddingTop: SPACING.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  moodFootText: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  chefRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginBottom: SPACING.md,
    flexWrap: "wrap",
  },
  chefAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.whiteSecondary,
  },
  chefBody: {
    flex: 1,
    minWidth: 160,
    gap: 4,
  },
  chefNm: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    color: COLORS.portalInk,
  },
  chefS: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  chefCapture: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  chefCam: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  chefCamText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.white,
  },
  chefUp: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
  },
  chefUpText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  chefMsg: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.portalInk,
    textAlignVertical: "top",
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: SPACING.md,
  },
  crDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    lineHeight: 17,
    marginBottom: SPACING.md,
  },
  crGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: SPACING.md,
  },
  crTile: {
    flexGrow: 1,
    flexBasis: "47%",
    minWidth: 140,
    minHeight: 140,
    borderRadius: RADIUS.md,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.sm,
    justifyContent: "space-between",
  },
  crHandle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  crBadges: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  crAct: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.neonOrange,
  },
  crSkip: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.ink4,
  },
  crFoot: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    flexWrap: "wrap",
  },
  crFootText: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    minWidth: 200,
  },
  schedTimeline: {
    gap: 0,
    marginBottom: SPACING.md,
  },
  schedSlot: {
    paddingVertical: SPACING.md,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.hairline,
    paddingLeft: SPACING.md,
    marginLeft: 6,
  },
  schedSlotActive: {
    borderLeftColor: COLORS.neonOrange,
    backgroundColor: "rgba(239, 159, 39, 0.08)",
    marginHorizontal: -6,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
  },
  slotTime: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 8,
    gap: 8,
  },
  slotLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    flexShrink: 1,
  },
  slotTm: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    fontVariant: ["tabular-nums"],
    color: COLORS.ink4,
  },
  slotContent: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  slotPill: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  slotPillText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  slotEmpty: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    fontStyle: "italic",
  },
});
