/* eslint-disable max-lines -- tablet settings screen mirrors large HTML prototype */
import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const settingsStyles = StyleSheet.create({
  rowRtl: {
    flexDirection: "row-reverse",
  },
  heroAvatarWrap: {
    alignItems: "center",
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  heroAvatarRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 3,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: COLORS.whiteSecondary,
  },
  heroAvatarImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginVertical: SPACING.md,
  },
  mergedAvPhoto: {
    width: 88,
    height: 88,
    borderRadius: 24,
  },
  heroAvatarText: {
    fontFamily: "Inter_900Black",
    fontSize: 28,
    color: COLORS.portalInk,
  },
  displaySub: {
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.xs,
  },
  displaySubLead: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
  },
  displaySubTrail: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink4,
  },
  langPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    maxWidth: 220,
  },
  langPillIcon: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  langPillBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  langPillLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  langPillValue: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  encryptedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.slateBadgeBorder,
    backgroundColor: COLORS.slateBadgeBg,
  },
  encryptedBadgeText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.slateBadgeText,
  },
  mergedCard: {
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.settingsIdentityBorder,
    backgroundColor: COLORS.black,
    overflow: "hidden",
    marginBottom: SPACING.md,
  },
  mergedMain: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: SPACING.lg,
    gap: SPACING.lg,
    alignItems: "flex-start",
  },
  mergedLeft: {
    flex: 1,
    minWidth: 220,
    flexDirection: "row",
    gap: SPACING.md,
  },
  mergedAvatarCol: {
    position: "relative",
  },
  mergedAvRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },

  mergedAvEdit: {
    position: "absolute",
    right: -5,
    bottom: 8,
    width: 24,
    height: 24,
    borderRadius: 14,
    backgroundColor: COLORS.textSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.white,
  },
  mergedBody: {
    flex: 1,
    minWidth: 120,
    gap: SPACING.xs,
  },
  mergedName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 18,
    color: COLORS.white,
    letterSpacing: -0.3,
  },
  mergedTitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: "rgba(255,255,255,0.72)",
  },
  pillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  pillText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: "rgba(255,255,255,0.9)",
  },
  pillGold: {
    backgroundColor: "rgba(255, 199, 0, 0.15)",
    borderColor: "rgba(255, 199, 0, 0.35)",
  },
  pillGreen: {
    backgroundColor: "rgba(34, 197, 94, 0.18)",
    borderColor: "rgba(34, 197, 94, 0.35)",
  },
  qrWrap: {
    width: 120,
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(255,255,255,0.25)",
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  qrImage: {
    width: 110,
    height: 110,
    resizeMode: "cover",
  },
  mergedActions: {
    gap: SPACING.xs,
  },
  darkAct: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  darkActText: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.white,
  },
  mergedMetaBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    gap: SPACING.lg,
  },
  metaCol: {
    minWidth: 100,
    flexGrow: 1,
    flexBasis: "15%",
  },
  metaColLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1,
    color: "rgba(255,255,255,0.45)",
    marginBottom: 4,
  },
  metaColValue: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: "rgba(255,255,255,0.92)",
  },
  metaColLive: {
    color: COLORS.secondary,
  },
  contactGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  contactGridCard: {
    flex: 1,
    minWidth: 280,
  },
  fieldHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  fieldHeadIcon: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  fieldHeadIconBlue: {
    backgroundColor: "rgba(14, 165, 233, 0.12)",
  },
  fieldHeadIconGreen: {
    backgroundColor: "rgba(34, 197, 94, 0.12)",
  },
  fieldHeadTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  fieldRowIcon: {
    marginTop: 2,
  },
  fieldData: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  fieldLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.8,
    color: COLORS.ink4,
  },
  fieldVal: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  fieldSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
    marginTop: 2,
  },
  fieldUpdate: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
  },
  fieldUpdateText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.portalInk,
  },
  banner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    marginTop: SPACING.md,
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
  },
  bannerWarn: {
    backgroundColor: "rgba(255, 138, 0, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 0, 0.25)",
  },
  bannerOk: {
    backgroundColor: "rgba(34, 197, 94, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.22)",
  },
  bannerText: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    color: COLORS.ink3,
  },
  pwHead: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: SPACING.md,
    marginBottom: SPACING.sm,
  },
  pwHeadIcon: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  pwHeadBody: {
    flex: 1,
    minWidth: 180,
    gap: 2,
  },
  pwHeadTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  pwHeadSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  strengthBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.strengthBadgeBorder,
    backgroundColor: COLORS.strengthBadgeBg,
  },
  strengthBadgeText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.strengthBadgeText,
  },
  pwDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
    marginBottom: SPACING.md,
  },
  pwDescStrong: {
    fontFamily: "Inter_700Bold",
    color: COLORS.portalInk,
  },
  pwMethods: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
  },
  pwMethod: {
    flex: 1,
    minWidth: 240,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
    gap: SPACING.sm,
  },
  pwMethodHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  pwMethodIc: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
  },
  pwMethodTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    flex: 1,
  },
  pwMethodSub: {
    fontFamily: "Inter_500Medium",
    fontSize: 11,
    lineHeight: 16,
    color: COLORS.ink3,
  },
  pwMethodBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.portalInk,
  },
  pwMethodBtnText: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.white,
  },
  pwMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: SPACING.md,
    marginTop: SPACING.md,
    paddingTop: SPACING.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  pwMetaText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  pwMetaStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  strengthTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.chartMist,
    overflow: "hidden",
    minWidth: 120,
    flex: 1,
    maxWidth: 200,
  },
  strengthFill: {
    height: "100%",
    width: "88%",
    borderRadius: 3,
    backgroundColor: COLORS.secondary,
  },
  strengthRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  strengthPct: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  panelTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
    marginBottom: SPACING.md,
  },
  panelTitleInline: {
    marginBottom: 0,
  },
  contactBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
    gap: SPACING.md,
  },
  contactBtnLast: {
    borderBottomWidth: 0,
  },
  contactIc: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  contactBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  contactName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  contactSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  contactArrow: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.ink4,
  },
  amCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  amBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  amAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  amAvatarText: {
    fontFamily: "Inter_900Black",
    fontSize: 14,
    color: COLORS.white,
  },
  amNm: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    color: COLORS.portalInk,
  },
  amSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.secondary,
    marginEnd: 4,
  },
  amStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  amStatCell: {
    minWidth: 90,
    gap: 2,
  },
  amStatLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  amStatVal: {
    fontFamily: "Inter_900Black",
    fontSize: 16,
    color: COLORS.portalInk,
  },
  urgentBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.neonYellow,
    marginBottom: SPACING.sm,
  },
  urgentBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  amNote: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
    textAlign: "center",
  },
  flexBetween: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  uxIntro: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
    marginBottom: SPACING.md,
  },
  uxCatLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink4,
    marginBottom: SPACING.sm,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginBottom: SPACING.md,
  },
  uxChip: {
    paddingVertical: 6,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
  },
  uxChipOn: {
    borderColor: COLORS.portalInk,
    backgroundColor: COLORS.portalInk,
  },
  uxChipText: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  uxChipTextOn: {
    color: COLORS.white,
  },
  uxInput: {
    marginBottom: SPACING.md,
  },
  badgeOk: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.25)",
    backgroundColor: "rgba(34, 197, 94, 0.1)",
  },
  badgeOkText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.secondary,
  },
  g3: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
    marginBottom: SPACING.lg,
  },
  g3Card: {
    flex: 1,
    minWidth: 260,
  },
  g21: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
    alignItems: "flex-start",
  },
  g21Main: {
    flex: 2,
    minWidth: 320,
  },
  g21Side: {
    flex: 1,
    minWidth: 260,
    gap: SPACING.md,
  },
  sessionRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  sessionRowLast: {
    borderBottomWidth: 0,
  },
  sessionRowCurrent: {
    backgroundColor: "rgba(79, 70, 229, 0.04)",
    marginHorizontal: -SPACING.lg,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.md,
    borderBottomWidth: 0,
  },
  sessionRowWarn: {
    backgroundColor: "rgba(255, 138, 0, 0.06)",
  },
  sessIc: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  sessIcWarn: {
    backgroundColor: "rgba(255, 138, 0, 0.15)",
  },
  sessBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  sessNm: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  sessThis: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.primary,
  },
  sessSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  sessMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
    marginTop: 4,
  },
  sessMetaText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  sessFlag: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
  },
  sessFlagText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.secondary,
  },
  sessKill: {
    alignSelf: "center",
    paddingVertical: 6,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
  },
  sessKillText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink3,
  },
  sessKillWarn: {
    borderColor: "rgba(255, 138, 0, 0.4)",
    backgroundColor: "rgba(255, 138, 0, 0.1)",
  },
  sessKillWarnText: {
    color: COLORS.neonOrange,
  },
  warnTag: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.neonOrange,
  },
  logoutDesc: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
    marginBottom: SPACING.md,
  },
  logoutChecks: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  logoutCheck: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  logoutCheckText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink3,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  logoutBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.white,
  },
  emergencyPanel: {
    borderColor: "rgba(255, 51, 85, 0.25)",
    backgroundColor: "rgba(255, 51, 85, 0.04)",
  },
  emergencyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 51, 85, 0.25)",
    backgroundColor: "rgba(255, 51, 85, 0.1)",
  },
  emergencyBadgeText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.neonRed,
  },
  emergencyBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.neonRed,
  },
  emergencyBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.white,
  },
  uxBadgePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
  },
  uxBadgePillText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink3,
  },
  sessionsBadge: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.whiteSecondary,
  },
  sessionsBadgeText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink3,
  },
  screen: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContent: {
    paddingBottom: SPACING.xxl,
  },
  cardFlex0: {
    flex: 0,
    flexGrow: 1,
  },
  uxSubmitBtn: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
  },
  uxSubmitBtnText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.white,
  },
});
