import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const staffStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.surfaceCanvas,
  },
  scrollContent: {
    paddingBottom: SPACING.xxl,
  },
  heroDisplay: {
    alignItems: "center",
    marginTop: SPACING.sm,
    marginBottom: 4,
  },
  heroAmountRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: SPACING.sm,
  },
  heroIconWrap: {
    transform: [{ translateY: 6 }],
  },
  heroNumber: {
    fontFamily: "Inter_900Black",
    fontSize: 56,
    letterSpacing: -3,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  meta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    marginTop: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  metaLeft: {
    flex: 1,
    minWidth: 120,
  },
  brandStack: {
    gap: 2,
  },
  brandName: {
    fontFamily: "Inter_900Black",
    fontSize: 12,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: COLORS.portalInk,
  },
  brandBranch: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink4,
    marginTop: 2,
  },
  metaMid: {
    flex: 1.4,
    alignItems: "center",
    gap: 4,
    minWidth: 200,
  },
  metaMidRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    flexWrap: "wrap",
  },
  metaMidText: {
    flexShrink: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    textAlign: "center",
    lineHeight: 18,
  },
  metaMidStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.trendPositiveDeep,
  },
  metaMidSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
  },
  metaMidLive: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  metaRight: {
    flex: 1,
    alignItems: "flex-end",
    minWidth: 120,
  },
  metaRightRtl: {
    alignItems: "flex-start",
  },
  metaTime: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    letterSpacing: -0.3,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  metaDate: {
    marginTop: 4,
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginBottom: SPACING.lg,
  },
  pgHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.lg,
    marginBottom: SPACING.md,
    flexWrap: "wrap",
  },
  pgHeadTitle: {
    flex: 1,
    minWidth: 220,
    gap: 0,
  },
  h1Light: {
    fontFamily: "Inter_400Regular",
    fontSize: 34,
    letterSpacing: -0.5,
    lineHeight: 38,
    color: COLORS.portalInk,
  },
  h1Strong: {
    fontFamily: "Inter_900Black",
    fontSize: 34,
    letterSpacing: -0.6,
    lineHeight: 38,
    color: COLORS.portalInk,
  },
  tag: {
    flex: 1,
    minWidth: 220,
    maxWidth: 320,
    paddingTop: 6,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
  },
  sectionHeadRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
    marginBottom: 10,
    flexWrap: "wrap",
    flexShrink: 1,
  },
  sectionTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    letterSpacing: -0.3,
    color: COLORS.portalInk,
  },
  sectionCaption: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    minWidth: 160,
  },
  rowRtl: {
    flexDirection: "row-reverse",
  },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255, 229, 0, 0.35)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
  },
  liveBadgeText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.2,
    color: COLORS.portalInk,
  },
  attendancePanel: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    marginBottom: SPACING.md,
  },
  panelKickerRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
    width: "100%",
  },
  panelKicker: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: COLORS.ink4,
    flexShrink: 1,
    flex: 1,
    minWidth: 0,
  },
  panelQuickStats: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: SPACING.sm,
    alignItems: "center",
    flexShrink: 0,
  },
  quickStatYellow: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.trendPositiveDeep,
  },
  quickStatOrange: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.neonOrange,
  },
  quickStatGrey: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink4,
  },

  /* ─────────── snapshot grid: 3 cards side-by-side, each row-internal ─────────── */
  snapshotGrid: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "stretch",
    gap: 10,
    width: "100%",
  },
  snapshotCard: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORS.whiteSecondary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    overflow: "hidden",
  },
  snapshotCardAccent: {
    borderStartWidth: 4,
    borderStartColor: COLORS.neonYellow,
  },
  snapshotIconWrap: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  snapshotBody: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    gap: 2,
  },
  snapshotValue: {
    fontFamily: "Inter_900Black",
    fontSize: 26,
    lineHeight: 28,
    letterSpacing: -1,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  snapshotValueAccent: {
    color: COLORS.trendPositiveDeep,
  },
  snapshotLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    lineHeight: 14,
    color: COLORS.ink3,
  },
  initialsStack: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 4,
    alignItems: "center",
    flexShrink: 0,
  },
  initialsPill: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.06)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  initialsText: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    color: COLORS.ink2,
  },
  morePill: {
    paddingHorizontal: 8,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
  },

  attendanceFooter: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginTop: SPACING.md,
    paddingTop: SPACING.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(0,0,0,0.06)",
    width: "100%",
  },
  topTodayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flexShrink: 1,
    flex: 1,
    minWidth: 0,
  },
  trophyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(239, 159, 39, 0.12)",
  },
  trophyText: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.8,
    color: COLORS.neonOrange,
  },
  topAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#0D9488",
    alignItems: "center",
    justifyContent: "center",
  },
  topAvatarTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.white,
  },
  topNameBlock: {
    gap: 10,
    maxWidth: 180,
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  topName: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  topSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  linkBold: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    textDecorationLine: "underline",
    flexShrink: 0,
  },
  registeredBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(0,0,0,0.045)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  registeredBadgeText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink2,
  },
  dirCardOuter: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    width: "100%",
  },
  dirMainRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    gap: SPACING.lg,
    width: "100%",
  },
  dirLeftCol: {
    flex: 1.6,
    minWidth: 0,
    flexShrink: 1,
    gap: 4,
  },
  dirBrowseTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    color: COLORS.portalInk,
  },
  dirBrowseDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    color: COLORS.ink4,
  },
  roleIconsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 6,
    flexShrink: 0,
  },
  roleIconCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
  },
  metricColumns: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: SPACING.lg,
    alignItems: "center",
    flexShrink: 0,
  },
  metricCol: {
    minWidth: 0,
    alignItems: "flex-start",
  },
  metricValue: {
    fontFamily: "Inter_900Black",
    fontSize: 20,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  metricLbl: {
    marginTop: 2,
    fontFamily: "Inter_700Bold",
    fontSize: 8,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: COLORS.ink5,
  },
  dirSeeAllInline: {
    flexShrink: 0,
    alignSelf: "center",
  },
  plusBadge: {
    paddingHorizontal: 8,
    height: 30,
    minWidth: 38,
    borderRadius: 15,
    backgroundColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
  },
  plusBadgeTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.white,
  },
});

export const styles = staffStyles;