import { StyleSheet } from "react-native";

import { COLORS, SPACING } from "@/constants/styles";

export const tierStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContent: {
    paddingBottom: SPACING.xxl,
  },
  heroDisplay: {
    alignItems: "center",
    marginTop: SPACING.sm,
    marginBottom: 4,
  },
  heroAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
  },
  heroNumber: {
    fontFamily: "Inter_900Black",
    fontSize: 72,
    letterSpacing: -3,
    fontVariant: ["tabular-nums"],
    color: COLORS.portalInk,
  },
  metaMid: {
    flex: 1.4,
    alignItems: "center",
    gap: 4,
    minWidth: 200,
  },
  metaMidRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    flexWrap: "wrap",
  },
  metaMidText: {
    flexShrink: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
    textAlign: "center",
    lineHeight: 18,
  },
  metaMidStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.accentAmber,
  },
  metaMidSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    textAlign: "center",
  },
  metaMidLive: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  roadmapLine: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    color: COLORS.ink3,
    marginTop: SPACING.sm,
    marginBottom: SPACING.lg,
    lineHeight: 18,
  },
  sectionHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  sectionHeadTitles: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    flex: 1,
    flexWrap: "wrap",
    minWidth: 220,
  },
  sectionTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    letterSpacing: -0.3,
    color: COLORS.portalInk,
  },
  sectionCaption: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  cardWrap: {
    marginBottom: 14,
  },
  miniGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 4,
  },
  progressWrap: {
    marginTop: SPACING.lg,
  },
  scorecardHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginTop: SPACING.lg,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  scorecardHeadLeft: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    flex: 1,
    minWidth: 220,
    flexWrap: "wrap",
  },
  liveChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: COLORS.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.trendPositive,
  },
  liveText: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.portalInk,
  },
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "stretch",
  },
  privilegesHeadRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    marginTop: SPACING.lg,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  smartHeadRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.sm,
    marginTop: SPACING.lg,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  smartGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "stretch",
  },
  smartCardWrap: {
    flexGrow: 1,
    flexBasis: "31%",
    minWidth: 280,
    alignSelf: "stretch",
  },
  rowRtl: {
    flexDirection: "row-reverse",
  },
});
