import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const addTeamMemberModalStyles = StyleSheet.create({
  addModalHeaderLeft: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    flex: 1,
  },
  addIconBox: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
  },
  addDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginVertical: SPACING.sm,
    marginHorizontal: SPACING.md,
    marginTop: 20,
  },
  bodyPad: {
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    padding: SPACING.sm
  },

  // step
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.xl,
    paddingTop: 12,
    marginBottom: SPACING.md,
    gap: 4,
  },
  stepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: COLORS.backgroundSecondary,
    maxWidth: 40,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  stepCircleActive: { backgroundColor: COLORS.portalInk },
  stepCircleIdle: { backgroundColor: COLORS.hairline },
  stepCircleDone: { backgroundColor: COLORS.trendPositiveDeep },
  stepNum: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.white,
  },
  stepNumIdle: { color: COLORS.ink4 },
  stepLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
    marginTop: 4,
    textAlign: "center",
  },
  stepLabelIdle: {
    fontFamily: "Inter_600SemiBold",
    color: COLORS.ink4,
  },

  sectionKicker: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.4,
    color: COLORS.ink2,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  sectionKickerSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
    marginTop: -8,
    marginBottom: 8,
  },
  sectionBlock: {
    marginBottom: SPACING.xl,
  },
  sectionBlockTight: {
    marginBottom: SPACING.lg,
  },

  uploadZone: {
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  uploadAvatarCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    opacity: 0.6,
    backgroundColor: COLORS.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 15,
    color: COLORS.portalInk,
  },
  fieldLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 0.8,
    color: COLORS.ink2,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  fieldLabelOpt: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    color: COLORS.ink5,
    textTransform: "none",
    letterSpacing: 0,
  },
  textField: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 10,
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: COLORS.portalInk,
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: SPACING.sm,
  },
  fieldGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  fieldHalf: {
    flex: 1,
    minWidth: 140,
  },
  primarySmBtn: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.portalInk,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    borderRadius: RADIUS.sm,
  },
  primarySmBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.white,
  },

  roleGrid: {
    gap: 12,
    marginBottom: 0,
  },
  roleGridRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 12,
  },
  roleTile: {
    flex: 0,
    width: "19.2%",
    height: 90,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  roleTileActive: {
    backgroundColor: COLORS.portalInk,
    borderColor: COLORS.portalInk,
  },
  roleTileLabel: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
    textAlign: "center",
  },
  roleTileLabelActive: { color: COLORS.white },
  footerActionsRow: {
    flexWrap: "nowrap",
    justifyContent: "space-between",
  },
  footerActionBtn: {
    flex: 1,
    minWidth: 0,
  },
  footerIconLabel: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },

  stationDropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 12,
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: SPACING.lg,
  },
  stationDropdownTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
  },

  shiftRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginBottom: SPACING.sm,
  },
  shiftField: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 12,
    backgroundColor: COLORS.whiteSecondary,
  },
  shiftFieldTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  daysRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
  },
  dayPill: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minWidth: 50,
  },
  dayPillActive: {
    backgroundColor: COLORS.portalInk,
    borderColor: COLORS.portalInk,
  },
  dayPillTxt: {
    fontFamily: "Inter_900Black",
    fontSize: 12,
    letterSpacing: 1,
    color: COLORS.ink3,
  },
  dayPillTxtActive: { color: COLORS.white },

  accessCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    backgroundColor: COLORS.white,
    gap: 6,
  },
  accessCardActive: {
    borderWidth: 1.5,
    borderColor: COLORS.portalInk,
  },
  accessCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    justifyContent: "space-between",
  },
  accessCardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flex: 1,
    minWidth: 0,
  },
  accessIconBox: {
    width: 30,
    height: 30,
    borderRadius: RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  accessIconBoxActive: {
    backgroundColor: COLORS.portalInk,
    borderColor: COLORS.portalInk,
  },
  accessTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  accessDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    color: COLORS.ink4,
  },
  accessBadgeMuted: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(0,0,0,0.05)",
  },
  accessBadgeMutedTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    color: COLORS.ink3,
  },
  accessBadgeGold: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255, 229, 0, 0.35)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
  },
  accessBadgeGoldTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    color: COLORS.trendPositiveDeep,
  },

  /* Invitation summary */
  summaryBox: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    backgroundColor: COLORS.whiteSecondary,
    marginTop: SPACING.sm,
  },
  summaryHeader: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.4,
    color: COLORS.ink4,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
    gap: SPACING.sm,
  },
  summaryDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginTop: 8,
    opacity: 0.5,
  },
  summaryLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  summaryValue: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    flexShrink: 1,
    textAlign: "right",
  },
  summaryFooter: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    color: COLORS.ink4,
  },
});

// success modal
export const optInSuccessStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.md,
  },
  card: {
    width: "100%",
    maxWidth: 460,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    alignItems: "center",
    gap: SPACING.md,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  iconWrap: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: SPACING.sm,
  },
  iconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.neonOrange,
    shadowColor: COLORS.neonOrange,
    shadowOpacity: 0.55,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  title: {
    fontFamily: "Inter_900Black",
    fontSize: 20,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
    textAlign: "center",
  },
  desc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
    textAlign: "center",
    paddingHorizontal: SPACING.sm,
  },
  descStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  statsRow: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: "rgba(255, 229, 0, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    marginTop: 4,
  },
  statCol: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 4,
  },
  statColMid: {
    flex: 1.4,
  },
  statValue: {
    fontFamily: "Inter_900Black",
    fontSize: 16,
    color: COLORS.portalInk,
    textAlign: "center",
    letterSpacing: -0.3,
  },
  statValueMono: {
    fontFamily: "Inter_900Black",
    fontSize: 14,
    color: COLORS.portalInk,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
    letterSpacing: -0.3,
  },
  statLabel: {
    fontFamily: "Inter_700Bold",
    fontSize: 8.5,
    letterSpacing: 1.2,
    color: COLORS.ink4,
    textAlign: "center",
    textTransform: "uppercase",
  },
  doneBtn: {
    width: "100%",
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  doneBtnTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
});