import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const allTeamMembersModalStyles = StyleSheet.create({
  bodyPad: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  bannerHeadingCol: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  bannerBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(239, 159, 39, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
    alignSelf: "flex-start",
  },
  bannerBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.neonOrange,
  },
  bannerBadgeTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.2,
    color: COLORS.neonOrange,
    textTransform: "uppercase",
  },
  bannerTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 26,
    letterSpacing: -0.5,
    color: COLORS.portalInk,
  },
  bannerSubtitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink3,
    maxWidth: "95%",
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: SPACING.sm,
    marginTop: 60
  },
  statBox: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORS.whiteSecondary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  statLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink5,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  statVal: {
    fontFamily: "Inter_900Black",
    fontSize: 22,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  searchAndFiltersRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flexWrap: "wrap",
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    backgroundColor: COLORS.whiteSecondary,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flex: 1,
    minWidth: 120,
  },
  searchInput: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.portalInk,
    padding: 0,
  },
  filterPillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
  },
  filterPill: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  filterPillActive: {
    backgroundColor: COLORS.portalInk,
    borderColor: COLORS.portalInk,
  },
  filterPillTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  filterPillTxtActive: {
    color: COLORS.white,
  },
  gridWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  memberCard: {
    flexBasis: "32%",
    flexGrow: 1,
    minWidth: 240,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    marginBottom: SPACING.sm
  },
  memberIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  memberTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  memberName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  memberRole: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  memberId: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 0.6,
    color: COLORS.ink5,
    marginTop: 2,
  },
  memberRatingCol: {
    alignItems: "flex-end",
    flexShrink: 0,
    gap: 0,
  },
  memberRatingVal: {
    fontFamily: "Inter_900Black",
    fontSize: 16,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  memberRatingLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 8,
    letterSpacing: 1.2,
    color: COLORS.ink5,
    textTransform: "uppercase",
  },
  emptyState: {
    paddingVertical: SPACING.xl,
    alignItems: "center",
    width: "100%",
  },
  emptyStateTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.ink4,
  },
});
