import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const assignStationModalStyles = StyleSheet.create({
  bodyPad: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  headerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  bannerHeadingCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  bannerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flexWrap: "wrap",
  },
  bannerTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 22,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
  },
  workloadBadgeHeader: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    borderWidth: 1,
  },
  workloadBadgeHeaderHeavy: {
    backgroundColor: "rgba(239, 68, 68, 0.10)",
    borderColor: "rgba(239, 68, 68, 0.30)",
  },
  workloadBadgeHeaderMedium: {
    backgroundColor: "rgba(249, 115, 22, 0.10)",
    borderColor: "rgba(249, 115, 22, 0.30)",
  },
  workloadBadgeHeaderLight: {
    backgroundColor: "rgba(34, 197, 94, 0.10)",
    borderColor: "rgba(34, 197, 94, 0.30)",
  },
  workloadBadgeHeaderUnassigned: {
    backgroundColor: COLORS.whiteSecondary,
    borderColor: COLORS.hairline,
  },
  workloadBadgeHeaderTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  workloadBadgeHeaderTxtHeavy: {
    color: "rgb(220, 38, 38)",
  },
  workloadBadgeHeaderTxtMedium: {
    color: "rgb(234, 88, 12)",
  },
  workloadBadgeHeaderTxtLight: {
    color: "rgb(22, 163, 74)",
  },
  workloadBadgeHeaderTxtUnassigned: {
    color: COLORS.ink4,
  },
  bannerSubtitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  currentlyAssignedSection: {
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.30)",
    backgroundColor: "rgba(239, 159, 39, 0.07)",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  currentlyAssignedLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.4,
    color: COLORS.neonOrange,
    textTransform: "uppercase",
  },
  currentAssigneeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  currentAssigneeIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  currentAssigneeTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  currentAssigneeName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  currentAssigneeRole: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  activeBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(34, 197, 94, 0.30)",
  },
  activeBadgeTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.2,
    color: "rgb(22, 163, 74)",
    textTransform: "uppercase",
  },
  selectReplacementHeading: {
    gap: 2,
  },
  selectReplacementTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 0.2,
    color: COLORS.portalInk,
    textTransform: "uppercase",
  },
  selectReplacementSubtitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    backgroundColor: COLORS.whiteSecondary,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  searchInput: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.portalInk,
    padding: 0,
  },
  listSection: {
    gap: 0,
  },
  listSectionHeader: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 8,
  },
  listSectionHeaderTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.2,
    color: COLORS.ink4,
    textTransform: "uppercase",
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    marginBottom: 6,
  },
  memberIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  memberTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  memberName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  memberMeta: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  starIcon: {
    marginLeft: 3,
  },
  hintBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.whiteSecondary,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  hintTxt: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
    flex: 1,
    lineHeight: 16,
  },
  setLoadSection: {
    gap: SPACING.sm,
  },
  setLoadTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 0.2,
    color: COLORS.portalInk,
    textTransform: "uppercase",
  },
  loadOptionsRow: {
    flexDirection: "row",
    gap: 6,
  },
  loadOption: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  loadOptionActive: {
    borderColor: COLORS.portalInk,
    backgroundColor: COLORS.whiteSecondary,
  },
  loadOptionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  loadOptionDotHeavy: {
    backgroundColor: "rgb(239, 68, 68)",
  },
  loadOptionDotMedium: {
    backgroundColor: "rgb(249, 115, 22)",
  },
  loadOptionDotLight: {
    backgroundColor: "rgb(234, 179, 8)",
  },
  loadOptionDotUnassigned: {
    backgroundColor: COLORS.ink5,
  },
  loadOptionLabel: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    color: COLORS.portalInk,
    textAlign: "center",
  },
  loadOptionSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    color: COLORS.ink4,
    textAlign: "center",
  },
  stationToolsSection: {
    gap: SPACING.sm,
  },
  stationToolsTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 0.2,
    color: COLORS.portalInk,
    textTransform: "uppercase",
  },
  stationToolsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  toolBtn: {
    flexBasis: "48%",
    flexGrow: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  toolBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  toolBtnDanger: {
    borderColor: "rgba(239, 68, 68, 0.30)",
    backgroundColor: "rgba(239, 68, 68, 0.04)",
  },
  toolBtnTxtDanger: {
    color: "rgb(220, 38, 38)",
  },
  successOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  successCard: {
    width: 320,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: 32,
    paddingHorizontal: 28,
    alignItems: "center",
    gap: SPACING.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 12,
  },
  successIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  successTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 18,
    color: COLORS.portalInk,
    letterSpacing: -0.3,
    textAlign: "center",
  },
  successBody: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
    color: COLORS.ink3,
    textAlign: "center",
    lineHeight: 19,
  },
  successBodyBold: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  successRefBox: {
    width: "100%",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.whiteSecondary,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  successRefLbl: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 9,
    letterSpacing: 1.4,
    color: COLORS.ink4,
    textTransform: "uppercase",
  },
  successRefVal: {
    fontFamily: "Inter_900Black",
    fontSize: 13,
    color: COLORS.portalInk,
    letterSpacing: 0.4,
  },
  successDoneBtn: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  successDoneBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  cancelBtn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  cancelBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  emptyState: {
    paddingVertical: SPACING.xl,
    alignItems: "center",
    width: "100%",
  },
  emptyStateTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.ink4,
  },
});