import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const burnoutAlertCardStyles = StyleSheet.create({
  card: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  headerTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: COLORS.portalInk,
    flexShrink: 1,
  },
  activeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(244, 63, 94, 0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(244, 63, 94, 0.30)",
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.financeRose,
  },
  activeBadgeTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.financeRose,
  },
  userRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: SPACING.sm,
  },
  userIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  userBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  userName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  userSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  durationBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(244, 63, 94, 0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(244, 63, 94, 0.30)",
  },
  durationBadgeTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.financeRose,
    fontVariant: ["tabular-nums"],
  },
  statRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    marginBottom: 6,
  },
  statLbl: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink2,
  },
  statVal: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  statValDanger: {
    color: COLORS.financeRose,
  },
  suggestBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(255, 229, 0, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  suggestText: {
    flex: 1,
    fontFamily: "Inter_500Medium",
    fontSize: 11,
    color: COLORS.ink2,
    lineHeight: 16,
  },
  suggestStrong: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: SPACING.sm,
  },
  ignoreBtn: {
    flex: 1,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
  },
  ignoreBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.ink2,
  },
  rotateBtn: {
    flex: 2,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
  },
  rotateBtnTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.white,
  },
});
