import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const digitalSignOffCardStyles = StyleSheet.create({
  card: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  headerTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: COLORS.portalInk,
    flexShrink: 1,
  },
  handoverBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255, 229, 0, 0.35)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
  },
  handoverBadgeTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.trendPositiveDeep,
  },
  subHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  subHeaderKicker: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: COLORS.ink4,
    flexShrink: 1,
  },
  subHeaderProgress: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.ink2,
    fontVariant: ["tabular-nums"],
  },
  taskItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    marginBottom: 6,
  },
  taskItemDone: {
    backgroundColor: "rgba(255, 229, 0, 0.10)",
    borderColor: "rgba(255, 199, 0, 0.45)",
  },
  checkBox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    flexShrink: 0,
  },
  checkBoxDone: {
    backgroundColor: COLORS.trendPositive,
    borderColor: COLORS.trendPositive,
  },
  taskTitle: {
    flex: 1,
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginVertical: SPACING.sm,
  },
  handoverKicker: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: COLORS.ink4,
    marginBottom: SPACING.sm,
  },
  handoverRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  handoverIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  handoverBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  handoverName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  handoverShift: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  signBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  signBtnTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
});
