import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const editProfileModalStyles = StyleSheet.create({
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flex: 1,
    minWidth: 0,
  },
  headerIconBox: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.whiteSecondary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  headerTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  headerTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 20,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
  },
  headerSubtitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink4,
  },
  body: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  bodyPad: {
    gap: SPACING.md,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginHorizontal: -SPACING.md,
    marginBottom: SPACING.xs,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: COLORS.ink3,
  },
  textField: {
    paddingVertical: 12,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  accessRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: SPACING.sm,
  },
  accessTile: {
    flex: 1,
    minWidth: 0,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    alignItems: "center",
    gap: 2,
  },
  accessTileActive: {
    borderWidth: 2,
    borderColor: COLORS.portalInk,
    backgroundColor: COLORS.whiteSecondary,
  },
  accessTileTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  accessTileSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    padding: SPACING.md,
    backgroundColor: "rgba(59, 130, 246, 0.06)",
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(59, 130, 246, 0.18)",
  },
  infoBannerTxt: {
    flex: 1,
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 17,
    color: COLORS.ink2,
  },
  footerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  footerBtn: {
    flex: 1,
    minWidth: 140,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  footerBtnStrong: {
    borderWidth: 2,
    borderColor: COLORS.portalInk,
  },
  footerBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
});
