import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const employeeDetailModalStyles = StyleSheet.create({
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  bodyPad: {
    paddingHorizontal: SPACING.md,
    paddingTop: 0,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginHorizontal: -SPACING.md,
    marginBottom: 0,
  },
  avatarLg: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  headerCenterCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  empIdLine: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 1.4,
    color: COLORS.ink5,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  empName: {
    fontFamily: "Inter_900Black",
    fontSize: 22,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
  },
  empRole: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  brandCol: {
    alignItems: "flex-end",
    gap: 4,
    flexShrink: 0,
  },
  brandPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  brandPillTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.2,
    color: COLORS.portalInk,
    textTransform: "uppercase",
  },
  brandSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  body: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  qrCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    padding: SPACING.md,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  qrBox: {
    width: 86,
    height: 86,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    flexShrink: 0,
  },
  qrBody: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  qrKicker: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 1.4,
    color: COLORS.ink5,
    textTransform: "uppercase",
  },
  qrTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 16,
    color: COLORS.portalInk,
  },
  qrDesc: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    lineHeight: 16,
    color: COLORS.ink4,
  },
  qrIssue: {
    marginTop: 4,
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    letterSpacing: 0.4,
    color: COLORS.ink5,
  },
  sectionTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: COLORS.ink3,
    marginBottom: -SPACING.xs,
  },
  fieldGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  fieldHalf: {
    flexBasis: "48%",
    flexGrow: 1,
    minWidth: 200,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    gap: 2,
  },
  fieldFull: {
    width: "100%",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    gap: 2,
  },
  fieldLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 1.2,
    color: COLORS.ink5,
    textTransform: "uppercase",
  },
  fieldVal: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  perfRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: SPACING.sm,
  },
  perfBox: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    gap: 2,
  },
  perfBoxStrong: {
    backgroundColor: COLORS.portalInk,
    borderColor: COLORS.portalInk,
  },
  perfVal: {
    fontFamily: "Inter_900Black",
    fontSize: 18,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  perfValStrong: {
    color: COLORS.white,
  },
  perfLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 1,
    color: COLORS.ink5,
    textTransform: "uppercase",
  },
  perfLblStrong: {
    color: COLORS.white,
  },
  startDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  startDateLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.ink4,
  },
  startDateVal: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  emergencyRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  emergencyTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    color: COLORS.portalInk,
  },
  footerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  footerBtn: {
    flex: 1,
    minWidth: 140,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  footerBtnStrong: {
    borderWidth: 2,
    borderColor: COLORS.portalInk,
  },
  footerBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
});
