import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const permissionMatrixModalStyles = StyleSheet.create({
  bodyPad: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
  },
  headerTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  headerBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(255, 229, 0, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(239, 159, 39, 0.35)",
    marginBottom: 4,
  },
  headerBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.neonOrange,
  },
  headerBadgeTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: COLORS.trendPositiveDeep,
  },
  headerBadgeEditing: {
    backgroundColor: "rgba(244, 63, 94, 0.10)",
    borderColor: "rgba(244, 63, 94, 0.35)",
  },
  headerBadgeDotEditing: {
    backgroundColor: COLORS.financeRose,
  },
  headerBadgeTxtEditing: {
    color: COLORS.financeRose,
  },
  headerTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 22,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
  },
  headerSubtitle: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.ink4,
  },
  tableWrap: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    borderRadius: RADIUS.md,
    overflow: "hidden",
    backgroundColor: COLORS.white,
  },
  tableHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.whiteSecondary,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.hairline,
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  permCellHead: {
    flex: 1.6,
    minWidth: 140,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
  },
  permCell: {
    flex: 1.6,
    minWidth: 140,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
  },
  roleCellHead: {
    flex: 1,
    minWidth: 80,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.xs,
    alignItems: "center",
    justifyContent: "center",
  },
  roleCell: {
    flex: 1,
    minWidth: 80,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xs,
    alignItems: "center",
    justifyContent: "center",
  },
  permLabelHead: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  roleLabelHead: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: COLORS.ink4,
    textAlign: "center",
  },
  permLabel: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  cellChip: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  cellChipFull: {
    backgroundColor: "rgba(255, 229, 0, 0.30)",
    borderColor: "rgba(239, 159, 39, 0.45)",
  },
  cellChipConditional: {
    backgroundColor: "rgba(255, 229, 0, 0.10)",
    borderColor: "rgba(239, 159, 39, 0.45)",
    borderStyle: "dashed",
  },
  cellChipRestricted: {
    backgroundColor: "transparent",
    borderColor: COLORS.hairline,
    borderStyle: "dashed",
  },
  cellChipEditing: {
    shadowColor: COLORS.trendPositive,
    shadowOpacity: 0.4,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
  },
  legendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
    paddingHorizontal: SPACING.xs,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendChip: {
    width: 18,
    height: 18,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  legendTxt: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  footerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    padding: SPACING.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.hairline,
  },
  footerBtn: {
    flex: 1,
    minWidth: 120,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  footerBtnStrong: {
    borderWidth: 2,
    borderColor: COLORS.portalInk,
  },
  footerBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: COLORS.portalInk,
  },
  footerBtnTxtStrong: {
    fontFamily: "Inter_800ExtraBold",
  },
});
