import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const roleManagementSystemCardStyles = StyleSheet.create({
  card: {
    flex: 2,
    minWidth: 0,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  headerTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    textTransform: "uppercase",
    color: COLORS.portalInk,
    flexShrink: 1,
  },
  headerLink: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  quickTile: {
    flexGrow: 1,
    flexBasis: "22%",
    minWidth: 110,
    borderEndWidth: 1,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    gap: 6,
  },
  quickTileHighlight: {
    backgroundColor: "rgba(244, 63, 94, 0.06)",
    borderColor: "rgba(244, 63, 94, 0.25)",
  },
  quickIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 100,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  quickIconWrapHighlight: {
    backgroundColor: "rgba(244, 63, 94, 0.10)",
    borderColor: "rgba(244, 63, 94, 0.30)",
  },
  quickTitle: {
    fontFamily: "Inter_800ExtraBold",
    color: COLORS.portalInk,
  },
  quickSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink3,
  },
  sectionHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  sectionHeadLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flexShrink: 1,
  },
  sectionKicker: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  sectionCountBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(0,0,0,0.06)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  sectionCountTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink2,
  },
  sectionLink: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
    color: COLORS.ink3,
  },
  rowItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    marginBottom: 6,
  },
  rowIconWrap: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  rowBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  rowTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 16,
    color: COLORS.portalInk,
  },
  rowMeta: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.ink4,
  },
  statusBadge: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
  },
  statusBadgeTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    letterSpacing: 0.6,
  },
  statusLive: {
    backgroundColor: "rgba(255, 229, 0, 0.30)",
    borderColor: "rgba(239, 159, 39, 0.35)",
  },
  statusLiveTxt: {
    color: COLORS.trendPositiveDeep,
  },
  statusScheduled: {
    backgroundColor: "rgba(0,0,0,0.05)",
    borderColor: COLORS.hairline,
  },
  statusScheduledTxt: {
    color: COLORS.ink2,
  },
  pctBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  pctBadgeTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 10,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
  recentItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    marginBottom: 6,
  },
  recentDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.neonOrange,
    flexShrink: 0,
  },
  recentTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  recentText: {
    fontFamily: "Inter_500Medium",
    fontSize: 10,
    color: COLORS.black,
  },
  recentTextStrong: {
    fontFamily: "Inter_500ExtraBold",
    color: COLORS.black,
    fontSize: 14
  },
  recentAt: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    color: COLORS.black,
  },
});
