import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const shiftDetailModalStyles = StyleSheet.create({
  bodyPad: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  headerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.portalInk,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  headerTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  headerTitle: {
    fontFamily: "Inter_900Black",
    fontSize: 20,
    letterSpacing: -0.4,
    color: COLORS.portalInk,
  },
  headerMeta: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: COLORS.ink4,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    color: COLORS.black,
    marginBottom: SPACING.sm,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: SPACING.sm,
  },
  statTile: {
    flex: 1,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    gap: 4,
  },
  statLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  statVal: {
    fontFamily: "Inter_900Black",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  sectionKicker: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    textTransform: "uppercase",
    color: COLORS.black,
    marginBottom: SPACING.sm,
  },
  employeesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  employeePill: {
    flexGrow: 1,
    flexBasis: "45%",
    minWidth: 140,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    marginTop: 3
  },
  employeeIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  employeeName: {
    flex: 1,
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  toolsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  toolBtn: {
    flexGrow: 1,
    flexBasis: "45%",
    minWidth: 140,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
  },
  toolBtnTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
  toolBtnDanger: {
    borderColor: "rgba(244, 63, 94, 0.35)",
  },
  toolBtnTxtDanger: {
    color: COLORS.financeRose,
  },
  closeBtn: {
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
  },
  closeBtnTxt: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 14,
    color: COLORS.portalInk,
  },
});
