import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING } from "@/constants/styles";

export const topRunnerCardStyles = StyleSheet.create({
  card: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  headerTitle: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: COLORS.portalInk,
    flexShrink: 1,
  },
  weekBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    backgroundColor: "rgba(0,0,0,0.045)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  weekBadgeTxt: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    color: COLORS.ink2,
  },
  podiumRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  podiumTile: {
    flex: 1,
    alignItems: "center",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.xs,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    gap: 4,
  },
  podiumTileSilver: {
    backgroundColor: "rgba(207, 207, 207, 0.20)",
    borderColor: "rgba(207, 207, 207, 0.50)",
  },
  podiumTileGold: {
    backgroundColor: "rgba(255, 229, 0, 0.25)",
    borderColor: "rgba(239, 159, 39, 0.45)",
    paddingVertical: SPACING.md,
  },
  podiumTileBronze: {
    backgroundColor: "rgba(255, 176, 94, 0.20)",
    borderColor: "rgba(255, 176, 94, 0.45)",
  },
  podiumAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
  },
  podiumRank: {
    fontFamily: "Inter_900Black",
    fontSize: 18,
    color: COLORS.portalInk,
    lineHeight: 22,
  },
  podiumName: {
    fontFamily: "Inter_800ExtraBold",
    fontSize: 11,
    color: COLORS.portalInk,
  },
  podiumSub: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 9,
    color: COLORS.ink4,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.hairline,
    marginVertical: SPACING.sm,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  statTile: {
    flex: 1,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.xs,
    borderRadius: RADIUS.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.hairline,
    backgroundColor: COLORS.whiteSecondary,
    alignItems: "center",
    gap: 2,
  },
  statLbl: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: COLORS.ink4,
  },
  statVal: {
    fontFamily: "Inter_900Black",
    fontSize: 14,
    color: COLORS.portalInk,
    fontVariant: ["tabular-nums"],
  },
});
