import { CONTROL_AR, CONTROL_EN } from "./control.translations";

export const SUPPORTED_LANGUAGES = ["en", "ar"] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: SupportedLanguage = "en";

export function isSupportedLanguage(language: string): language is SupportedLanguage {
  return (SUPPORTED_LANGUAGES as readonly string[]).includes(language);
}

export const resources = {
  en: {
    translation: {
      common: {
        appName: "Pick & Go",
        continue: "Continue",
        cancel: "Cancel",
      },
      auth: {
        signIn: "Sign in",
        welcomeBack: "Welcome back",
        welcome: "Welcome",
        signInToBusiness: "Sign in to your PICK&GO Business.",
        workEmailOrWhatsapp: "Work email or registered WhatsApp number",
        emailOrPhonePlaceholder: "jon@french-bakery.ae  |  +971 50 123 4567",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        keepMeSignedIn: "Keep me signed in",
        forgotPassword: "Forgot password?",
        newToPickAndGo: "new to PICK&GO",
        registerBusiness: "Register your business",
        footerCopyright: "© 2026 PICK&GO Business",
        footerEntity: "Entity financial tech solutions",
        footerGeo: "UK · UAE · USA",
        forgotPasswordTitle: "Forgot password",
        forgotPasswordSubtitle:
          "Enter your work email or phone and we will send a verification code.",
        sendCode: "Send verification code",
        backToSignIn: "Back to sign in",
        verificationTitle: "Verify your account",
        verificationSubtitle: "We sent a 6-digit code to {{contact}}.",
        verificationCode: "Verification code",
        verificationCodePlaceholder: "Enter 6-digit code",
        verifyCode: "Verify code",
        resendCode: "Resend code",
        resetPasswordTitle: "Reset password",
        resetPasswordSubtitle: "Create a new password for your account.",
        newPassword: "New password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Re-enter your new password",
        updatePassword: "Update password",
        passwordResetSuccess: "Password reset successful. Please sign in.",
        requiredFieldError: "Please fill in all required fields.",
        passwordMismatchError: "Passwords do not match.",
        passwordPolicyError: "Please meet all password requirements before continuing.",
        recoveryResetTitle: "Reset your password",
        recoveryResetDesc:
          "Enter your email or WhatsApp number. We will send you a verification code.",
        recoveryEmailOrWhatsappShort: "Email or WhatsApp number",
        recoveryForgotContactPlaceholder: "jon@french-bakery.ae",
        recoveryVerifyTitle: "Enter verification code",
        recoveryVerifyLinePrefix: "We sent a 6-digit code to",
        recoveryDidntReceive: "Didn't receive the code?",
        recoveryResendIn: "Resend in {{seconds}}s",
        recoveryChangeContact: "Change email or number",
        recoveryNewPwdTitle: "Create new password",
        recoveryNewPwdDesc: "Choose a strong password to secure your account.",
        recoveryNewPwdPlaceholder: "At least 8 characters",
        recoveryConfirmPwdPlaceholder: "Re-enter password",
        passwordStrengthEmpty: "Enter a password",
        passwordStrengthWeak: "Weak password",
        passwordStrengthFair: "Fair password",
        passwordStrengthGood: "Good password",
        passwordStrengthStrong: "Strong password",
        ruleAtLeast8Chars: "At least 8 characters",
        ruleOneUppercase: "One uppercase letter",
        ruleOneNumber: "One number",
        ruleOneSpecial: "One special character",
        recoverySuccessTitle: "All done!",
        recoverySuccessDesc:
          "Your password has been updated successfully. You can now sign in with your new password.",
      },
      tabs: {
        explore: "Explore",
        bookings: "Bookings",
        favorite: "Favorite",
        profile: "Profile",
      },
      intelligence: {
        heroProjected: "11,240",
        brandName: "French Bakery",
        brandBranch: "Dubai Downtown · Branch",
        projectedLinePrefix: "Projected end-of-day · ",
        projectedHighlight: "+{{amount}} pending fulfillment",
        syncLineStart: "Auto-refresh every 5s · Last sync 2s ago · ",
        live: "Live",
        titleLine1: "Live &",
        titleStrong: "intelligence.",
        subtitle:
          "Real-time monitoring of operations, cash flow, and subscription automation. Everything updates as your kitchen runs.",
        operationsTitle: "Operations Stream",
        operationsCaption: "Workflow tracking across the kitchen",
        preparingTitle: "Preparing now",
        preparingMeta: "8 active",
        preparingValue: "8",
        preparingStat: "avg {{minutes}}m left",
        readyTitle: "Ready for handover",
        readyMeta: "awaiting",
        readyValue: "4",
        readyStat: "rider {{minutes}}m ETA",
        handedTitle: "Handed over",
        handedMeta: "+12 last hr",
        handedValue: "73",
        handedStat: "96.8% success",
        futureTitle: "Future orders",
        futureMeta: "this week",
        futureValue: "12",
        futureStat: "next 7:30 PM",
        financialTitle: "Financial Pulse",
        financialCaption: "Liquidity & forecasting in real time",
        currencyBadge: "UAE Dirham",
        salesTitle: "Live sales",
        salesMeta: "73 delivered",
        salesValue: "8,427",
        salesStat: "Confirmed",
        projectedCardTitle: "Projected revenue",
        projectedCardMeta: "EOD",
        projectedCardValue: "11,240",
        projectedCardStatPrefix: "+{{amount}} pending",
        liabilitiesTitle: "Collected vs liabilities",
        liabilitiesMetaLive: "LIVE",
        collectedLabel: "Collected",
        collectedValue: "6,320",
        owedLabel: "Owed",
        owedValue: "2,107",
        pctCollected: "75",
        ringCollectedCaption: "collected",
        funnelTitle: "Live Prep Funnel",
        funnelSub: "Order stage distribution",
        funnelInPipePrefix: "In pipe ",
        funnelDonePrefix: "Done ",
        funnelStagesReceived: "Received",
        funnelStagesConfirmed: "Confirmed",
        funnelStagesPreparing: "Preparing",
        funnelStagesReady: "Ready",
        funnelStagesHanded: "Handed",
        pickupTitle: "Pickup Modes",
        pickupSub: "Curbside vs in-store",
        pickupCenterPct: "62",
        pickupCenterLbl: "Curbside",
        pickupLegCurbside: "Curbside {{pct}}%",
        pickupLegStore: "In-store {{pct}}%",
        autopickTitle: "Auto-Pick Engine",
        autopickSub: "Subscription automation",
        autopickCenterMain: "47",
        autopickCenterSub: "Active · 78%",
        autopickWeekPrefix: "This week ",
        autopickNewPrefix: "+3 ",
        autopickNewWord: "new",
        topSellingTitle: "Top Selling",
        topSellingSub: "Most requested this hour",
        topSellingHero: "40",
        topSellingHeroMeta: "orders in last 60m",
        peakTitle: "Peak Flow Predictor",
        peakSub: "Hourly order frequency · today",
        peakHero: "1",
        peakHeroSuffix: "PM",
        peakHeroMetaPrefix: "next peak · ",
        peakHeroMetaHighlight: "+38%",
      },
      control: CONTROL_EN,
      financePage: {
        heroBalance: "{{currency}} 47,283",
        availableBalancePrefix: "Available balance · ",
        todayNetPositive: "+{{currency}} {{amount}} today",
        nextPayoutMeta: "Next payout in {{days}} · {{date}}",
        nextPayoutDays: "{{count}} days",
        nextPayoutOneDay: "1 day",
        nextPayoutLessThanDay: "< 1 day",
        nextPayoutDue: "Due now",
        titleLine1: "Finance &",
        titleStrong: "payouts.",
        subtitle:
          "Revenue streams, settlement cycles, and cash-flow visibility. Every transaction tracked · every payout reconciled.",
        gross30dTitle: "Gross (30d)",
        gross30dTopRight: "+34%",
        gross30dValue: "{{currency}} 187K",
        gross30dFooter: "• Up",
        platformFeesTitle: "Platform fees",
        platformFeesTopRight: "0% Gold",
        platformFeesValue: "Zero",
        platformFeesFooter: "Gold tier",
        vatTitle: "VAT (5%)",
        vatTopRight: "Auto",
        vatValue: "-8.9K",
        vatFooter: "Remitted",
        netEarningsTitle: "Net earnings",
        netEarningsTopRight: "83.2%",
        netEarningsValue: "{{currency}} 158,451*",
        netEarningsFooter: "▼ Net",
        recentTransactions: "↓ RECENT TRANSACTIONS",
        export: "Export",
        payoutCardTitle: "Next payout in",
        expectedPayout: "EXPECTED {{currency}} {{amount}}",
        unitDayShort: "d",
        unitHourShort: "H",
        unitMinuteShort: "M",
        unitSecondShort: "S",
      },
      staff: {
        heroProjected: "18",
        brandName: "French Bakery",
        brandBranch: "Dubai Downtown · Branch",
        projectedLinePrefix: "On duty now · ",
        projectedHighlight: "{{count}} clocked in · {{late}} late · {{off}} off",
        syncLineStart: "Auto-refresh every 5s · Last sync 2s ago · ",
        live: "Live",
        titleLine1: "Staff &",
        titleStrong: "privileges.",
        subtitle:
          "Your team, your operation — with real-time visibility and fine-grained privilege control. Manage attendance, tasks, roles, and performance all from one place.",
        operationsTitle: "Attendance & Live Status",
        operationsCaption: "Real-time team location & availability",
        digitalClockKicker: "DIGITAL CLOCK-IN/OUT · TODAY'S SHIFT",
        quickStatClocked: "{{count}} clocked in",
        quickStatLate: "{{count}} late",
        quickStatOff: "{{count}} off",
        clockedInLabel: "Clocked in — on duty",
        lateArrivalsLabel: "Late arrivals · needs follow-up",
        offTodayLabel: "Off today · scheduled rest",
        topTodayBadge: "TOP TODAY",
        topPerformerSub: "{{orders}} orders · {{role}}",
        viewAllStaff: "View all staff",
        seeAllMembers: "See all team members",
        teamDirectoryTitle: "Team Directory",
        teamDirectoryCaption: "Full employee records · ID cards · QR credentials",
        browseMembersTitle: "Browse all team members",
        browseMembersDesc:
          "Each member has a unique ID, QR badge for clock-in verification, full contact details, and performance history.",
        registeredBadge: "{{count}} registered",
        metricMembers: "MEMBERS",
        metricRoles: "ROLES",
        metricAvgRating: "AVG RATING",
        metricAttendance: "ATTENDANCE",
        roleMore: "+{{count}}",
        snapshotMore: "+{{count}}",

        fullTeamLiveStatus: "FULL TEAM · LIVE STATUS",
        allStaffTitle: "All Staff · Today's Shift",
        allStaffDescription:
          "Complete real-time view of every team member — status, location, shift time, and order performance.",
        onDutyStat: "ON DUTY",
        lateStat: "LATE",
        offTodayStat: "OFF TODAY",
        totalTeamStat: "TOTAL TEAM",
        searchPlaceholder: "Search by name, role…",
        filterAll: "All",
        filterOnDuty: "On duty",
        filterLate: "Late",
        filterOff: "Off",
        colMember: "MEMBER",
        colLocation: "LOCATION",
        colStatus: "STATUS",
        colShiftTime: "SHIFT TIME",
        colPerformance: "PERFORMANCE",
        locationInside: "Inside",
        locationOnDelivery: "On delivery",
        locationReturning: "Returning",
        statusClockedIn: "Clocked in",
        statusOnDelivery: "On delivery",
        statusReturning: "Returning",
        statusOffToday: "Off today",
        ordersUnit: "orders",
        topPerformance: "TOP",
        admin: "admin",

        addMemberTitle: "Add team member",
        addMemberSubtitle: "Onboard a new staff member to French Bakery · Dubai Downtown.",
        stepProfile: "Profile",
        stepRole: "Role",
        stepAccess: "Access",
        photoOptional: "PHOTO (OPTIONAL)",
        uploadPhotoTitle: "Upload a profile photo",
        uploadPhotoHint: "JPG or PNG · or skip for the role icon",
        chooseFile: "Choose file",
        firstNamePlaceholder: "e.g. Ahmed",
        lastNamePlaceholder: "e.g. Khalil",
        firstNameLabel: "FIRST NAME",
        lastNameLabel: "LAST NAME",
        phoneLabel: "PHONE NUMBER",
        phonePlaceholder: "+971 50 123 4567",
        emailLabel: "EMAIL",
        optionalSuffix: "optional",
        emailPlaceholder: "ahmed@example.com",

        btnClose: "Close",
        btnBack: "Back",
        btnContinue: "Continue",
        btnSendInvite: "Send invite",
        btnDone: "Done",
        btnAddMemberShort: "Add team member",
        cancel: "Cancel",
        topTag: "TOP",
        selectRoleLabel: "SELECT ROLE",
        stationLabel: "STATION",
        stationSubLabel: "Choose where this team member usually works",
        shiftScheduleLabel: "SHIFT SCHEDULE",
        dayMon: "Mon",
        dayTue: "Tue",
        dayWed: "Wed",
        dayThu: "Thu",
        dayFri: "Fri",
        daySat: "Sat",
        daySun: "Sun",
        roleHeadChef: "Head Chef",
        roleLineCook: "Line Cook",
        rolePrepCook: "Prep Cook",
        rolePastryChef: "Pastry Chef",
        roleExpeditor: "Expeditor",
        roleDishwasher: "Dishwasher",
        roleRunner: "Runner",
        roleBarista: "Barista",
        roleCashier: "Cashier",
        roleServer: "Server",
        roleHost: "Host",
        roleBusboy: "Busboy",
        roleManager: "Manager",
        accessLevelLabel: "ACCESS LEVEL",
        accessBasicTitle: "Basic access",
        accessBasicDesc: "Clock in/out, view assigned tasks, and receive shift updates.",
        accessStandardTitle: "Standard access",
        accessStandardDesc: "Includes basic access plus order view and daily performance.",
        accessAdvancedTitle: "Advanced access",
        accessAdvancedDesc: "Manage team workflow, update statuses, and assign stations.",
        accessAdminTitle: "Admin access",
        accessAdminDesc: "Full permissions to manage roles, schedules, and privileges.",
        accessDefault: "Default",
        accessFullAccess: "Full access",
        invitationSummaryLabel: "STAFF INVITATION SUMMARY",
        summaryName: "Name",
        summaryRole: "Role",
        summaryShift: "Shift",
        summaryDaysPerWeek: "{{count}} days/week",
        summaryAccess: "Access",
        summaryFooterText:
          "Invitation will be sent immediately. The team member can accept and start after approval.",
        optInTitle: "Invitation sent",
        optInDescPrefix: "Your invite for",
        optInTeamInvite: "Team invite",
        optInDescSuffix: "has been submitted for approval.",
        optInAvgApproval: "AVG APPROVAL",
        optInRequestId: "REQUEST ID",
        optInEmail: "Email",
        optInNotification: "NOTIFICATION",
      },
    },
  },
  ar: {
    translation: {
      common: {
        appName: "بيك آند جو",
        continue: "متابعة",
        cancel: "إلغاء",
      },
      auth: {
        signIn: "تسجيل الدخول",
        welcomeBack: "مرحبًا بعودتك",
        welcome: "مرحبًا",
        signInToBusiness: "سجّل الدخول إلى PICK&GO Business.",
        workEmailOrWhatsapp: "البريد الإلكتروني للعمل أو رقم واتساب المسجل",
        emailOrPhonePlaceholder: "jon@french-bakery.ae  |  +971 50 123 4567",
        password: "كلمة المرور",
        passwordPlaceholder: "أدخل كلمة المرور",
        keepMeSignedIn: "إبقني مسجلًا",
        forgotPassword: "نسيت كلمة المرور؟",
        newToPickAndGo: "جديد على PICK&GO",
        registerBusiness: "سجّل نشاطك التجاري",
        footerCopyright: "© 2026 PICK&GO Business",
        footerEntity: "Entity financial tech solutions",
        footerGeo: "المملكة المتحدة · الإمارات · الولايات المتحدة",
        forgotPasswordTitle: "نسيت كلمة المرور",
        forgotPasswordSubtitle:
          "أدخل بريد العمل أو رقم الهاتف وسنرسل لك رمز التحقق.",
        sendCode: "إرسال رمز التحقق",
        backToSignIn: "العودة لتسجيل الدخول",
        verificationTitle: "تحقق من الحساب",
        verificationSubtitle: "أرسلنا رمزًا من 6 أرقام إلى {{contact}}.",
        verificationCode: "رمز التحقق",
        verificationCodePlaceholder: "أدخل رمزًا من 6 أرقام",
        verifyCode: "تحقق من الرمز",
        resendCode: "إعادة إرسال الرمز",
        resetPasswordTitle: "إعادة تعيين كلمة المرور",
        resetPasswordSubtitle: "أنشئ كلمة مرور جديدة لحسابك.",
        newPassword: "كلمة المرور الجديدة",
        confirmPassword: "تأكيد كلمة المرور",
        confirmPasswordPlaceholder: "أعد إدخال كلمة المرور الجديدة",
        updatePassword: "تحديث كلمة المرور",
        passwordResetSuccess: "تمت إعادة تعيين كلمة المرور. سجّل الدخول الآن.",
        requiredFieldError: "يرجى تعبئة كل الحقول المطلوبة.",
        passwordMismatchError: "كلمتا المرور غير متطابقتين.",
        passwordPolicyError: "يرجى استيفاء جميع متطلبات كلمة المرور قبل المتابعة.",
        recoveryResetTitle: "إعادة تعيين كلمة المرور",
        recoveryResetDesc:
          "أدخل بريدك الإلكتروني أو رقم واتساب. سنرسل لك رمز التحقق.",
        recoveryEmailOrWhatsappShort: "البريد الإلكتروني أو رقم واتساب",
        recoveryForgotContactPlaceholder: "jon@french-bakery.ae",
        recoveryVerifyTitle: "أدخل رمز التحقق",
        recoveryVerifyLinePrefix: "أرسلنا رمزًا مكوّنًا من 6 أرقام إلى",
        recoveryDidntReceive: "لم يصلك الرمز؟",
        recoveryResendIn: "إعادة الإرسال خلال {{seconds}} ث",
        recoveryChangeContact: "تغيير البريد أو الرقم",
        recoveryNewPwdTitle: "إنشاء كلمة مرور جديدة",
        recoveryNewPwdDesc: "اختر كلمة مرور قوية لحماية حسابك.",
        recoveryNewPwdPlaceholder: "8 أحرف على الأقل",
        recoveryConfirmPwdPlaceholder: "أعد إدخال كلمة المرور",
        passwordStrengthEmpty: "أدخل كلمة المرور",
        passwordStrengthWeak: "كلمة مرور ضعيفة",
        passwordStrengthFair: "كلمة مرور متوسطة",
        passwordStrengthGood: "كلمة مرور جيدة",
        passwordStrengthStrong: "كلمة مرور قوية",
        ruleAtLeast8Chars: "8 أحرف على الأقل",
        ruleOneUppercase: "حرف كبير واحد على الأقل",
        ruleOneNumber: "رقم واحد على الأقل",
        ruleOneSpecial: "رمز خاص واحد على الأقل",
        recoverySuccessTitle: "تم بنجاح!",
        recoverySuccessDesc:
          "تم تحديث كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.",
      },
      tabs: {
        explore: "استكشاف",
        bookings: "الحجوزات",
        favorite: "المفضلة",
        profile: "الملف الشخصي",
      },
      intelligence: {
        heroProjected: "11,240",
        brandName: "المخبز الفرنسي",
        brandBranch: "وسط دبي · فرع",
        projectedLinePrefix: "توقعات نهاية اليوم · ",
        projectedHighlight: "+{{amount}} قيد التنفيذ",
        syncLineStart: "تحديث تلقائي كل 5 ث · آخر مزامنة قبل ثنتين · ",
        live: "مباشر",
        titleLine1: "الذكاء ",
        titleStrong: "المباشر.",
        subtitle:
          "مراقبة لحظية للعمليات والتدفق النقدي وأتمتة الاشتراكات. كل شيء يتحدث مع تشغيل مطبخك.",
        operationsTitle: "تدفق العمليات",
        operationsCaption: "تتبّع سير العمل عبر المطبخ",
        preparingTitle: "قيد التحضير الآن",
        preparingMeta: "8 نشطة",
        preparingValue: "8",
        preparingStat: "متوسط {{minutes}} د متبقية",
        readyTitle: "جاهزة للتسليم",
        readyMeta: "في الانتظار",
        readyValue: "4",
        readyStat: "السائق خلال {{minutes}} د",
        handedTitle: "تم التسليم",
        handedMeta: "+12 آخر ساعة",
        handedValue: "73",
        handedStat: "نجاح 96.8٪",
        futureTitle: "طلبات مستقبلية",
        futureMeta: "هذا الأسبوع",
        futureValue: "12",
        futureStat: "التالي 7:30 م",
        financialTitle: "النبض المالي",
        financialCaption: "السيولة والتوقعات في الوقت الفعلي",
        currencyBadge: "درهم إماراتي",
        salesTitle: "مبيعات مباشرة",
        salesMeta: "73 مسلّمة",
        salesValue: "8,427",
        salesStat: "مؤكدة",
        projectedCardTitle: "إيراد متوقع",
        projectedCardMeta: "نهاية اليوم",
        projectedCardValue: "11,240",
        projectedCardStatPrefix: "+{{amount}} قيد التنفيذ",
        liabilitiesTitle: "المتحصل مقابل الالتزامات",
        liabilitiesMetaLive: "مباشر",
        collectedLabel: "المتحصل",
        collectedValue: "6,320",
        owedLabel: "المستحق",
        owedValue: "2,107",
        pctCollected: "75",
        ringCollectedCaption: "محصّل",
        funnelTitle: "قمع التحضير المباشر",
        funnelSub: "توزيع مراحل الطلب",
        funnelInPipePrefix: "في المسار ",
        funnelDonePrefix: "منجز ",
        funnelStagesReceived: "مستلم",
        funnelStagesConfirmed: "مؤكد",
        funnelStagesPreparing: "قيد التحضير",
        funnelStagesReady: "جاهز",
        funnelStagesHanded: "مسلّم",
        pickupTitle: "أنماط الاستلام",
        pickupSub: "أمام المتجر مقابل داخل المتجر",
        pickupCenterPct: "62",
        pickupCenterLbl: "أمام المتجر",
        pickupLegCurbside: "أمام المتجر {{pct}}٪",
        pickupLegStore: "داخل المتجر {{pct}}٪",
        autopickTitle: "محرك الاختيار التلقائي",
        autopickSub: "أتمتة الاشتراكات",
        autopickCenterMain: "47",
        autopickCenterSub: "نشط · 78٪",
        autopickWeekPrefix: "هذا الأسبوع ",
        autopickNewPrefix: "+3 ",
        autopickNewWord: "جديد",
        topSellingTitle: "الأكثر مبيعًا",
        topSellingSub: "الأكثر طلبًا خلال هذه الساعة",
        topSellingHero: "40",
        topSellingHeroMeta: "طلبات آخر 60 د",
        peakTitle: "متوقع الذروة",
        peakSub: "وتيرة الطلبات بالساعة · اليوم",
        peakHero: "1",
        peakHeroSuffix: "م",
        peakHeroMetaPrefix: "الذروة التالية · ",
        peakHeroMetaHighlight: "+38%",
      },
      control: CONTROL_AR,
      financePage: {
        heroBalance: "{{currency}} 47,283",
        availableBalancePrefix: "الرصيد المتاح · ",
        todayNetPositive: "+{{currency}} {{amount}} اليوم",
        nextPayoutMeta: "الدفعة التالية خلال {{days}} · {{date}}",
        nextPayoutDays: "{{count}} أيام",
        nextPayoutOneDay: "يوم واحد",
        nextPayoutLessThanDay: "أقل من يوم",
        nextPayoutDue: "مستحقة الآن",
        titleLine1: "والدفعات .",
        titleStrong: "التمويل.",
        subtitle:
          "مصادر الإيراد، دورات التسوية، ورؤية التدفق النقدي. كل معاملة متتبعة · كل دفعة مُسوّاة.",
        gross30dTitle: "الإجمالي (30 يومًا)",
        gross30dTopRight: "+34٪",
        gross30dValue: "{{currency}} 187 ألف",
        gross30dFooter: "• صعود",
        platformFeesTitle: "رسوم المنصة",
        platformFeesTopRight: "0٪ ذهبي",
        platformFeesValue: "صفر",
        platformFeesFooter: "المستوى الذهبي",
        vatTitle: "ضريبة القيمة المضافة (٪5)",
        vatTopRight: "تلقائي",
        vatValue: "-8.9 ألف",
        vatFooter: "تم التوريد",
        netEarningsTitle: "صافي الأرباح",
        netEarningsTopRight: "83.2٪",
        netEarningsValue: "{{currency}} 158,451*",
        netEarningsFooter: "▼ الصافي",
        recentTransactions: "↓ أحدث المعاملات",
        export: "تصدير",
        payoutCardTitle: "الدفعة التالية خلال",
        expectedPayout: "المتوقع {{currency}} {{amount}}",
        unitDayShort: "ي",
        unitHourShort: "س",
        unitMinuteShort: "د",
        unitSecondShort: "ث",
      },
      staff: {
        heroProjected: "18",
        brandName: "المخبز الفرنسي",
        brandBranch: "وسط دبي · فرع",
        projectedLinePrefix: "على الخدمة الآن · ",
        projectedHighlight: "{{count}} مسجّل حضور · {{late}} متأخر · {{off}} إجازة",
        syncLineStart: "تحديث تلقائي كل 5 ث · آخر مزامنة قبل ثنتين · ",
        live: "مباشر",
        titleLine1: "الموظفون",
        titleStrong: "والصلاحيات.",
        subtitle:
          "فريقك وعملياتك — برؤية لحظية وتحكّم دقيق بالصلاحيات. أدر الحضور والمهام والأدوار والأداء من مكان واحد.",
        operationsTitle: "الحضور والحالة المباشرة",
        operationsCaption: "مواقع الفريق والتوافر في الوقت الفعلي",
        digitalClockKicker: "تسجيل دخول/خروج رقمي · وردية اليوم",
        quickStatClocked: "{{count}} مسجّل حضور",
        quickStatLate: "{{count}} متأخر",
        quickStatOff: "{{count}} خارج اليوم",
        clockedInLabel: "مسجّل حضور — على الخدمة",
        lateArrivalsLabel: "وصول متأخر · يحتاج متابعة",
        offTodayLabel: "خارج اليوم · راحة مجدولة",
        topTodayBadge: "الأفضل اليوم",
        topPerformerSub: "{{orders}} طلبات · {{role}}",
        viewAllStaff: "عرض كل الموظفين",
        seeAllMembers: "عرض كل أعضاء الفريق",
        teamDirectoryTitle: "دليل الفريق",
        teamDirectoryCaption: "سجلات كاملة · بطاقات تعريف · بيانات QR",
        browseMembersTitle: "تصفّح كل أعضاء الفريق",
        browseMembersDesc:
          "لكل عضو معرّف فريد، شارة QR لتسجيل الحضور، بيانات اتصال كاملة، وسجل أداء.",
        registeredBadge: "{{count}} مسجّل",
        metricMembers: "أعضاء",
        metricRoles: "أدوار",
        metricAvgRating: "متوسط التقييم",
        metricAttendance: "الحضور",
        roleMore: "+{{count}}",
        snapshotMore: "+{{count}}",

        fullTeamLiveStatus: "الفريق الكامل · حالة مباشرة",
        allStaffTitle: "كل الموظفين · وردية اليوم",
        allStaffDescription:
          "رؤية كاملة في الوقت الفعلي لكل عضو — الحالة، الموقع، وقت الوردية، وأداء الطلبات.",
        onDutyStat: "على الخدمة",
        lateStat: "متأخر",
        offTodayStat: "خارج اليوم",
        totalTeamStat: "إجمالي الفريق",
        searchPlaceholder: "ابحث بالاسم أو الدور…",
        filterAll: "الكل",
        filterOnDuty: "على الخدمة",
        filterLate: "متأخر",
        filterOff: "خارج",
        colMember: "العضو",
        colLocation: "الموقع",
        colStatus: "الحالة",
        colShiftTime: "الوردية",
        colPerformance: "الأداء",
        locationInside: "داخل",
        locationOnDelivery: "في التوصيل",
        locationReturning: "في العودة",
        statusClockedIn: "مسجّل حضور",
        statusOnDelivery: "في التوصيل",
        statusReturning: "في العودة",
        statusOffToday: "خارج اليوم",
        ordersUnit: "طلبات",
        topPerformance: "TOP",
        admin: "مسؤول",

        addMemberTitle: "إضافة عضو للفريق",
        addMemberSubtitle: "إعداد عضو جديد في المخبز الفرنسي · وسط دبي.",
        stepProfile: "الملف",
        stepRole: "الدور",
        stepAccess: "الوصول",
        photoOptional: "الصورة (اختياري)",
        uploadPhotoTitle: "حمّل صورة الملف",
        uploadPhotoHint: "JPG أو PNG · أو يُستخدم أيقونة الدور",
        chooseFile: "اختر ملفًا",
        firstNamePlaceholder: "مثال: أحمد",
        lastNamePlaceholder: "مثال: خليل",
        firstNameLabel: "الاسم الأول",
        lastNameLabel: "اسم العائلة",
        phoneLabel: "رقم الهاتف",
        phonePlaceholder: "+971 50 123 4567",
        emailLabel: "البريد",
        optionalSuffix: "اختياري",
        emailPlaceholder: "ahmed@example.com",

        btnClose: "إغلاق",
        btnBack: "رجوع",
        btnContinue: "متابعة",
        btnSendInvite: "إرسال الدعوة",
        btnDone: "تم",
        btnAddMemberShort: "إضافة عضو",
        cancel: "إلغاء",
        topTag: "الأفضل",
        selectRoleLabel: "اختيار الدور",
        stationLabel: "المحطة",
        stationSubLabel: "اختر المكان الذي يعمل فيه هذا العضو غالبًا",
        shiftScheduleLabel: "جدول الوردية",
        dayMon: "الإثنين",
        dayTue: "الثلاثاء",
        dayWed: "الأربعاء",
        dayThu: "الخميس",
        dayFri: "الجمعة",
        daySat: "السبت",
        daySun: "الأحد",
        roleHeadChef: "رئيس الطهاة",
        roleLineCook: "طاهٍ خطي",
        rolePrepCook: "طاهٍ تحضير",
        rolePastryChef: "طاهي حلويات",
        roleExpeditor: "منسق الطلبات",
        roleDishwasher: "غاسل أطباق",
        roleRunner: "عدّاء طلبات",
        roleBarista: "باريستا",
        roleCashier: "أمين صندوق",
        roleServer: "مقدّم خدمة",
        roleHost: "مضيف",
        roleBusboy: "مساعد صالة",
        roleManager: "مدير",
        accessLevelLabel: "مستوى الصلاحية",
        accessBasicTitle: "صلاحية أساسية",
        accessBasicDesc: "تسجيل حضور/انصراف، عرض المهام المعيّنة، واستلام تحديثات الوردية.",
        accessStandardTitle: "صلاحية قياسية",
        accessStandardDesc: "تشمل الصلاحية الأساسية بالإضافة لعرض الطلبات وأداء اليوم.",
        accessAdvancedTitle: "صلاحية متقدمة",
        accessAdvancedDesc: "إدارة سير الفريق، تحديث الحالات، وتوزيع المحطات.",
        accessAdminTitle: "صلاحية مدير",
        accessAdminDesc: "صلاحيات كاملة لإدارة الأدوار والجداول ومستويات الوصول.",
        accessDefault: "افتراضي",
        accessFullAccess: "وصول كامل",
        invitationSummaryLabel: "ملخص دعوة الموظف",
        summaryName: "الاسم",
        summaryRole: "الدور",
        summaryShift: "الوردية",
        summaryDaysPerWeek: "{{count}} أيام/أسبوع",
        summaryAccess: "الصلاحية",
        summaryFooterText: "سيتم إرسال الدعوة فورًا، ويمكن للموظف البدء بعد الموافقة.",
        optInTitle: "تم إرسال الدعوة",
        optInDescPrefix: "تم إرسال",
        optInTeamInvite: "دعوة الفريق",
        optInDescSuffix: "للموافقة.",
        optInAvgApproval: "متوسط الموافقة",
        optInRequestId: "رقم الطلب",
        optInEmail: "البريد",
        optInNotification: "الإشعار",
      },
    },
  },
};
