export const SUPPORTED_LANGUAGES = ["en", "ar"] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: SupportedLanguage = "en";

export function isSupportedLanguage(language: string): language is SupportedLanguage {
  return (SUPPORTED_LANGUAGES as readonly string[]).includes(language);
}

export const resources = {
  en: {
    translation: {
      common: {
        appName: "Pick & Go",
        continue: "Continue",
        cancel: "Cancel",
      },
      auth: {
        signIn: "Sign in",
        welcomeBack: "Welcome back",
        welcome: "Welcome",
        signInToBusiness: "Sign in to your PICK&GO Business.",
        workEmailOrWhatsapp: "Work email or registered WhatsApp number",
        emailOrPhonePlaceholder: "jon@french-bakery.ae  |  +971 50 123 4567",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        keepMeSignedIn: "Keep me signed in",
        forgotPassword: "Forgot password?",
        newToPickAndGo: "new to PICK&GO",
        registerBusiness: "Register your business",
        footerCopyright: "© 2026 PICK&GO Business",
        footerEntity: "Entity financial tech solutions",
        footerGeo: "UK · UAE · USA",
        forgotPasswordTitle: "Forgot password",
        forgotPasswordSubtitle:
          "Enter your work email or phone and we will send a verification code.",
        sendCode: "Send verification code",
        backToSignIn: "Back to sign in",
        verificationTitle: "Verify your account",
        verificationSubtitle: "We sent a 6-digit code to {{contact}}.",
        verificationCode: "Verification code",
        verificationCodePlaceholder: "Enter 6-digit code",
        verifyCode: "Verify code",
        resendCode: "Resend code",
        resetPasswordTitle: "Reset password",
        resetPasswordSubtitle: "Create a new password for your account.",
        newPassword: "New password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Re-enter your new password",
        updatePassword: "Update password",
        passwordResetSuccess: "Password reset successful. Please sign in.",
        requiredFieldError: "Please fill in all required fields.",
        passwordMismatchError: "Passwords do not match.",
        passwordPolicyError: "Please meet all password requirements before continuing.",
        recoveryResetTitle: "Reset your password",
        recoveryResetDesc:
          "Enter your email or WhatsApp number. We will send you a verification code.",
        recoveryEmailOrWhatsappShort: "Email or WhatsApp number",
        recoveryForgotContactPlaceholder: "jon@french-bakery.ae",
        recoveryVerifyTitle: "Enter verification code",
        recoveryVerifyLinePrefix: "We sent a 6-digit code to",
        recoveryDidntReceive: "Didn't receive the code?",
        recoveryResendIn: "Resend in {{seconds}}s",
        recoveryChangeContact: "Change email or number",
        recoveryNewPwdTitle: "Create new password",
        recoveryNewPwdDesc: "Choose a strong password to secure your account.",
        recoveryNewPwdPlaceholder: "At least 8 characters",
        recoveryConfirmPwdPlaceholder: "Re-enter password",
        passwordStrengthEmpty: "Enter a password",
        passwordStrengthWeak: "Weak password",
        passwordStrengthFair: "Fair password",
        passwordStrengthGood: "Good password",
        passwordStrengthStrong: "Strong password",
        ruleAtLeast8Chars: "At least 8 characters",
        ruleOneUppercase: "One uppercase letter",
        ruleOneNumber: "One number",
        ruleOneSpecial: "One special character",
        recoverySuccessTitle: "All done!",
        recoverySuccessDesc:
          "Your password has been updated successfully. You can now sign in with your new password.",
      },
      tabs: {
        explore: "Explore",
        bookings: "Bookings",
        favorite: "Favorite",
        profile: "Profile",
      },
    },
  },
  ar: {
    translation: {
      common: {
        appName: "بيك آند جو",
        continue: "متابعة",
        cancel: "إلغاء",
      },
      auth: {
        signIn: "تسجيل الدخول",
        welcomeBack: "مرحبًا بعودتك",
        welcome: "مرحبًا",
        signInToBusiness: "سجّل الدخول إلى PICK&GO Business.",
        workEmailOrWhatsapp: "البريد الإلكتروني للعمل أو رقم واتساب المسجل",
        emailOrPhonePlaceholder: "jon@french-bakery.ae  |  +971 50 123 4567",
        password: "كلمة المرور",
        passwordPlaceholder: "أدخل كلمة المرور",
        keepMeSignedIn: "إبقني مسجلًا",
        forgotPassword: "نسيت كلمة المرور؟",
        newToPickAndGo: "جديد على PICK&GO",
        registerBusiness: "سجّل نشاطك التجاري",
        footerCopyright: "© 2026 PICK&GO Business",
        footerEntity: "Entity financial tech solutions",
        footerGeo: "المملكة المتحدة · الإمارات · الولايات المتحدة",
        forgotPasswordTitle: "نسيت كلمة المرور",
        forgotPasswordSubtitle:
          "أدخل بريد العمل أو رقم الهاتف وسنرسل لك رمز التحقق.",
        sendCode: "إرسال رمز التحقق",
        backToSignIn: "العودة لتسجيل الدخول",
        verificationTitle: "تحقق من الحساب",
        verificationSubtitle: "أرسلنا رمزًا من 6 أرقام إلى {{contact}}.",
        verificationCode: "رمز التحقق",
        verificationCodePlaceholder: "أدخل رمزًا من 6 أرقام",
        verifyCode: "تحقق من الرمز",
        resendCode: "إعادة إرسال الرمز",
        resetPasswordTitle: "إعادة تعيين كلمة المرور",
        resetPasswordSubtitle: "أنشئ كلمة مرور جديدة لحسابك.",
        newPassword: "كلمة المرور الجديدة",
        confirmPassword: "تأكيد كلمة المرور",
        confirmPasswordPlaceholder: "أعد إدخال كلمة المرور الجديدة",
        updatePassword: "تحديث كلمة المرور",
        passwordResetSuccess: "تمت إعادة تعيين كلمة المرور. سجّل الدخول الآن.",
        requiredFieldError: "يرجى تعبئة كل الحقول المطلوبة.",
        passwordMismatchError: "كلمتا المرور غير متطابقتين.",
        passwordPolicyError: "يرجى استيفاء جميع متطلبات كلمة المرور قبل المتابعة.",
        recoveryResetTitle: "إعادة تعيين كلمة المرور",
        recoveryResetDesc:
          "أدخل بريدك الإلكتروني أو رقم واتساب. سنرسل لك رمز التحقق.",
        recoveryEmailOrWhatsappShort: "البريد الإلكتروني أو رقم واتساب",
        recoveryForgotContactPlaceholder: "jon@french-bakery.ae",
        recoveryVerifyTitle: "أدخل رمز التحقق",
        recoveryVerifyLinePrefix: "أرسلنا رمزًا مكوّنًا من 6 أرقام إلى",
        recoveryDidntReceive: "لم يصلك الرمز؟",
        recoveryResendIn: "إعادة الإرسال خلال {{seconds}} ث",
        recoveryChangeContact: "تغيير البريد أو الرقم",
        recoveryNewPwdTitle: "إنشاء كلمة مرور جديدة",
        recoveryNewPwdDesc: "اختر كلمة مرور قوية لحماية حسابك.",
        recoveryNewPwdPlaceholder: "8 أحرف على الأقل",
        recoveryConfirmPwdPlaceholder: "أعد إدخال كلمة المرور",
        passwordStrengthEmpty: "أدخل كلمة المرور",
        passwordStrengthWeak: "كلمة مرور ضعيفة",
        passwordStrengthFair: "كلمة مرور متوسطة",
        passwordStrengthGood: "كلمة مرور جيدة",
        passwordStrengthStrong: "كلمة مرور قوية",
        ruleAtLeast8Chars: "8 أحرف على الأقل",
        ruleOneUppercase: "حرف كبير واحد على الأقل",
        ruleOneNumber: "رقم واحد على الأقل",
        ruleOneSpecial: "رمز خاص واحد على الأقل",
        recoverySuccessTitle: "تم بنجاح!",
        recoverySuccessDesc:
          "تم تحديث كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.",
      },
      tabs: {
        explore: "استكشاف",
        bookings: "الحجوزات",
        favorite: "المفضلة",
        profile: "الملف الشخصي",
      },
    },
  },
};
