export const SUPPORTED_LANGUAGES = ["en", "ar"] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

export const DEFAULT_LANGUAGE: SupportedLanguage = "en";

export function isSupportedLanguage(language: string): language is SupportedLanguage {
  return (SUPPORTED_LANGUAGES as readonly string[]).includes(language);
}

export const resources = {
  en: {
    translation: {
      common: {
        appName: "Pick & Go",
        continue: "Continue",
        cancel: "Cancel",
      },
      auth: {
        signIn: "Sign in",
        welcomeBack: "Welcome back",
        welcome: "Welcome",
        signInToBusiness: "Sign in to your PICK&GO Business.",
        workEmailOrWhatsapp: "Work email or registered WhatsApp number",
        emailOrPhonePlaceholder: "jon@french-bakery.ae  |  +971 50 123 4567",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        keepMeSignedIn: "Keep me signed in",
        forgotPassword: "Forgot password?",
        newToPickAndGo: "new to PICK&GO",
        registerBusiness: "Register your business",
        footerCopyright: "© 2026 PICK&GO Business",
        footerEntity: "Entity financial tech solutions",
        footerGeo: "UK · UAE · USA",
        forgotPasswordTitle: "Forgot password",
        forgotPasswordSubtitle:
          "Enter your work email or phone and we will send a verification code.",
        sendCode: "Send verification code",
        backToSignIn: "Back to sign in",
        verificationTitle: "Verify your account",
        verificationSubtitle: "We sent a 6-digit code to {{contact}}.",
        verificationCode: "Verification code",
        verificationCodePlaceholder: "Enter 6-digit code",
        verifyCode: "Verify code",
        resendCode: "Resend code",
        resetPasswordTitle: "Reset password",
        resetPasswordSubtitle: "Create a new password for your account.",
        newPassword: "New password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Re-enter your new password",
        updatePassword: "Update password",
        passwordResetSuccess: "Password reset successful. Please sign in.",
        requiredFieldError: "Please fill in all required fields.",
        passwordMismatchError: "Passwords do not match.",
        passwordPolicyError: "Please meet all password requirements before continuing.",
        recoveryResetTitle: "Reset your password",
        recoveryResetDesc:
          "Enter your email or WhatsApp number. We will send you a verification code.",
        recoveryEmailOrWhatsappShort: "Email or WhatsApp number",
        recoveryForgotContactPlaceholder: "jon@french-bakery.ae",
        recoveryVerifyTitle: "Enter verification code",
        recoveryVerifyLinePrefix: "We sent a 6-digit code to",
        recoveryDidntReceive: "Didn't receive the code?",
        recoveryResendIn: "Resend in {{seconds}}s",
        recoveryChangeContact: "Change email or number",
        recoveryNewPwdTitle: "Create new password",
        recoveryNewPwdDesc: "Choose a strong password to secure your account.",
        recoveryNewPwdPlaceholder: "At least 8 characters",
        recoveryConfirmPwdPlaceholder: "Re-enter password",
        passwordStrengthEmpty: "Enter a password",
        passwordStrengthWeak: "Weak password",
        passwordStrengthFair: "Fair password",
        passwordStrengthGood: "Good password",
        passwordStrengthStrong: "Strong password",
        ruleAtLeast8Chars: "At least 8 characters",
        ruleOneUppercase: "One uppercase letter",
        ruleOneNumber: "One number",
        ruleOneSpecial: "One special character",
        recoverySuccessTitle: "All done!",
        recoverySuccessDesc:
          "Your password has been updated successfully. You can now sign in with your new password.",
      },
      tabs: {
        explore: "Explore",
        bookings: "Bookings",
        favorite: "Favorite",
        profile: "Profile",
      },
      intelligence: {
        heroProjected: "11,240",
        brandName: "French Bakery",
        brandBranch: "Dubai Downtown · Branch",
        projectedLinePrefix: "Projected end-of-day · ",
        projectedHighlight: "+{{amount}} pending fulfillment",
        syncLineStart: "Auto-refresh every 5s · Last sync 2s ago · ",
        live: "Live",
        titleLine1: "Live &",
        titleStrong: "intelligence.",
        subtitle:
          "Real-time monitoring of operations, cash flow, and subscription automation. Everything updates as your kitchen runs.",
        operationsTitle: "Operations Stream",
        operationsCaption: "Workflow tracking across the kitchen",
        preparingTitle: "Preparing now",
        preparingMeta: "8 active",
        preparingValue: "8",
        preparingStat: "avg {{minutes}}m left",
        readyTitle: "Ready for handover",
        readyMeta: "awaiting",
        readyValue: "4",
        readyStat: "rider {{minutes}}m ETA",
        handedTitle: "Handed over",
        handedMeta: "+12 last hr",
        handedValue: "73",
        handedStat: "96.8% success",
        futureTitle: "Future orders",
        futureMeta: "this week",
        futureValue: "12",
        futureStat: "next 7:30 PM",
        financialTitle: "Financial Pulse",
        financialCaption: "Liquidity & forecasting in real time",
        currencyBadge: "UAE Dirham",
        salesTitle: "Live sales",
        salesMeta: "73 delivered",
        salesValue: "8,427",
        salesStat: "Confirmed",
        projectedCardTitle: "Projected revenue",
        projectedCardMeta: "EOD",
        projectedCardValue: "11,240",
        projectedCardStatPrefix: "+{{amount}} pending",
        liabilitiesTitle: "Collected vs liabilities",
        liabilitiesMetaLive: "LIVE",
        collectedLabel: "Collected",
        collectedValue: "6,320",
        owedLabel: "Owed",
        owedValue: "2,107",
        pctCollected: "75",
        ringCollectedCaption: "collected",
        funnelTitle: "Live Prep Funnel",
        funnelSub: "Order stage distribution",
        funnelInPipePrefix: "In pipe ",
        funnelDonePrefix: "Done ",
        funnelStagesReceived: "Received",
        funnelStagesConfirmed: "Confirmed",
        funnelStagesPreparing: "Preparing",
        funnelStagesReady: "Ready",
        funnelStagesHanded: "Handed",
        pickupTitle: "Pickup Modes",
        pickupSub: "Curbside vs in-store",
        pickupCenterPct: "62",
        pickupCenterLbl: "Curbside",
        pickupLegCurbside: "Curbside {{pct}}%",
        pickupLegStore: "In-store {{pct}}%",
        autopickTitle: "Auto-Pick Engine",
        autopickSub: "Subscription automation",
        autopickCenterMain: "47",
        autopickCenterSub: "Active · 78%",
        autopickWeekPrefix: "This week ",
        autopickNewPrefix: "+3 ",
        autopickNewWord: "new",
        topSellingTitle: "Top Selling",
        topSellingSub: "Most requested this hour",
        topSellingHero: "40",
        topSellingHeroMeta: "orders in last 60m",
        peakTitle: "Peak Flow Predictor",
        peakSub: "Hourly order frequency · today",
        peakHero: "1",
        peakHeroSuffix: "PM",
        peakHeroMetaPrefix: "next peak · ",
        peakHeroMetaHighlight: "+38%",
      },
    },
  },
  ar: {
    translation: {
      common: {
        appName: "بيك آند جو",
        continue: "متابعة",
        cancel: "إلغاء",
      },
      auth: {
        signIn: "تسجيل الدخول",
        welcomeBack: "مرحبًا بعودتك",
        welcome: "مرحبًا",
        signInToBusiness: "سجّل الدخول إلى PICK&GO Business.",
        workEmailOrWhatsapp: "البريد الإلكتروني للعمل أو رقم واتساب المسجل",
        emailOrPhonePlaceholder: "jon@french-bakery.ae  |  +971 50 123 4567",
        password: "كلمة المرور",
        passwordPlaceholder: "أدخل كلمة المرور",
        keepMeSignedIn: "إبقني مسجلًا",
        forgotPassword: "نسيت كلمة المرور؟",
        newToPickAndGo: "جديد على PICK&GO",
        registerBusiness: "سجّل نشاطك التجاري",
        footerCopyright: "© 2026 PICK&GO Business",
        footerEntity: "Entity financial tech solutions",
        footerGeo: "المملكة المتحدة · الإمارات · الولايات المتحدة",
        forgotPasswordTitle: "نسيت كلمة المرور",
        forgotPasswordSubtitle:
          "أدخل بريد العمل أو رقم الهاتف وسنرسل لك رمز التحقق.",
        sendCode: "إرسال رمز التحقق",
        backToSignIn: "العودة لتسجيل الدخول",
        verificationTitle: "تحقق من الحساب",
        verificationSubtitle: "أرسلنا رمزًا من 6 أرقام إلى {{contact}}.",
        verificationCode: "رمز التحقق",
        verificationCodePlaceholder: "أدخل رمزًا من 6 أرقام",
        verifyCode: "تحقق من الرمز",
        resendCode: "إعادة إرسال الرمز",
        resetPasswordTitle: "إعادة تعيين كلمة المرور",
        resetPasswordSubtitle: "أنشئ كلمة مرور جديدة لحسابك.",
        newPassword: "كلمة المرور الجديدة",
        confirmPassword: "تأكيد كلمة المرور",
        confirmPasswordPlaceholder: "أعد إدخال كلمة المرور الجديدة",
        updatePassword: "تحديث كلمة المرور",
        passwordResetSuccess: "تمت إعادة تعيين كلمة المرور. سجّل الدخول الآن.",
        requiredFieldError: "يرجى تعبئة كل الحقول المطلوبة.",
        passwordMismatchError: "كلمتا المرور غير متطابقتين.",
        passwordPolicyError: "يرجى استيفاء جميع متطلبات كلمة المرور قبل المتابعة.",
        recoveryResetTitle: "إعادة تعيين كلمة المرور",
        recoveryResetDesc:
          "أدخل بريدك الإلكتروني أو رقم واتساب. سنرسل لك رمز التحقق.",
        recoveryEmailOrWhatsappShort: "البريد الإلكتروني أو رقم واتساب",
        recoveryForgotContactPlaceholder: "jon@french-bakery.ae",
        recoveryVerifyTitle: "أدخل رمز التحقق",
        recoveryVerifyLinePrefix: "أرسلنا رمزًا مكوّنًا من 6 أرقام إلى",
        recoveryDidntReceive: "لم يصلك الرمز؟",
        recoveryResendIn: "إعادة الإرسال خلال {{seconds}} ث",
        recoveryChangeContact: "تغيير البريد أو الرقم",
        recoveryNewPwdTitle: "إنشاء كلمة مرور جديدة",
        recoveryNewPwdDesc: "اختر كلمة مرور قوية لحماية حسابك.",
        recoveryNewPwdPlaceholder: "8 أحرف على الأقل",
        recoveryConfirmPwdPlaceholder: "أعد إدخال كلمة المرور",
        passwordStrengthEmpty: "أدخل كلمة المرور",
        passwordStrengthWeak: "كلمة مرور ضعيفة",
        passwordStrengthFair: "كلمة مرور متوسطة",
        passwordStrengthGood: "كلمة مرور جيدة",
        passwordStrengthStrong: "كلمة مرور قوية",
        ruleAtLeast8Chars: "8 أحرف على الأقل",
        ruleOneUppercase: "حرف كبير واحد على الأقل",
        ruleOneNumber: "رقم واحد على الأقل",
        ruleOneSpecial: "رمز خاص واحد على الأقل",
        recoverySuccessTitle: "تم بنجاح!",
        recoverySuccessDesc:
          "تم تحديث كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.",
      },
      tabs: {
        explore: "استكشاف",
        bookings: "الحجوزات",
        favorite: "المفضلة",
        profile: "الملف الشخصي",
      },
      intelligence: {
        heroProjected: "11,240",
        brandName: "المخبز الفرنسي",
        brandBranch: "وسط دبي · فرع",
        projectedLinePrefix: "توقعات نهاية اليوم · ",
        projectedHighlight: "+{{amount}} قيد التنفيذ",
        syncLineStart: "تحديث تلقائي كل 5 ث · آخر مزامنة قبل ثنتين · ",
        live: "مباشر",
        titleLine1: "الذكاء ",
        titleStrong: "المباشر.",
        subtitle:
          "مراقبة لحظية للعمليات والتدفق النقدي وأتمتة الاشتراكات. كل شيء يتحدث مع تشغيل مطبخك.",
        operationsTitle: "تدفق العمليات",
        operationsCaption: "تتبّع سير العمل عبر المطبخ",
        preparingTitle: "قيد التحضير الآن",
        preparingMeta: "8 نشطة",
        preparingValue: "8",
        preparingStat: "متوسط {{minutes}} د متبقية",
        readyTitle: "جاهزة للتسليم",
        readyMeta: "في الانتظار",
        readyValue: "4",
        readyStat: "السائق خلال {{minutes}} د",
        handedTitle: "تم التسليم",
        handedMeta: "+12 آخر ساعة",
        handedValue: "73",
        handedStat: "نجاح 96.8٪",
        futureTitle: "طلبات مستقبلية",
        futureMeta: "هذا الأسبوع",
        futureValue: "12",
        futureStat: "التالي 7:30 م",
        financialTitle: "النبض المالي",
        financialCaption: "السيولة والتوقعات في الوقت الفعلي",
        currencyBadge: "درهم إماراتي",
        salesTitle: "مبيعات مباشرة",
        salesMeta: "73 مسلّمة",
        salesValue: "8,427",
        salesStat: "مؤكدة",
        projectedCardTitle: "إيراد متوقع",
        projectedCardMeta: "نهاية اليوم",
        projectedCardValue: "11,240",
        projectedCardStatPrefix: "+{{amount}} قيد التنفيذ",
        liabilitiesTitle: "المتحصل مقابل الالتزامات",
        liabilitiesMetaLive: "مباشر",
        collectedLabel: "المتحصل",
        collectedValue: "6,320",
        owedLabel: "المستحق",
        owedValue: "2,107",
        pctCollected: "75",
        ringCollectedCaption: "محصّل",
        funnelTitle: "قمع التحضير المباشر",
        funnelSub: "توزيع مراحل الطلب",
        funnelInPipePrefix: "في المسار ",
        funnelDonePrefix: "منجز ",
        funnelStagesReceived: "مستلم",
        funnelStagesConfirmed: "مؤكد",
        funnelStagesPreparing: "قيد التحضير",
        funnelStagesReady: "جاهز",
        funnelStagesHanded: "مسلّم",
        pickupTitle: "أنماط الاستلام",
        pickupSub: "أمام المتجر مقابل داخل المتجر",
        pickupCenterPct: "62",
        pickupCenterLbl: "أمام المتجر",
        pickupLegCurbside: "أمام المتجر {{pct}}٪",
        pickupLegStore: "داخل المتجر {{pct}}٪",
        autopickTitle: "محرك الاختيار التلقائي",
        autopickSub: "أتمتة الاشتراكات",
        autopickCenterMain: "47",
        autopickCenterSub: "نشط · 78٪",
        autopickWeekPrefix: "هذا الأسبوع ",
        autopickNewPrefix: "+3 ",
        autopickNewWord: "جديد",
        topSellingTitle: "الأكثر مبيعًا",
        topSellingSub: "الأكثر طلبًا خلال هذه الساعة",
        topSellingHero: "40",
        topSellingHeroMeta: "طلبات آخر 60 د",
        peakTitle: "متوقع الذروة",
        peakSub: "وتيرة الطلبات بالساعة · اليوم",
        peakHero: "1",
        peakHeroSuffix: "م",
        peakHeroMetaPrefix: "الذروة التالية · ",
        peakHeroMetaHighlight: "+38%",
      },
    },
  },
};
